package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AuthorizedData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String role;

	@javax.persistence.Id
	@javax.persistence.GeneratedValue(generator = "AUTHORIZED_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.SequenceGenerator(sequenceName = "AUTHORIZED_ID_SEQ", name = "AUTHORIZED_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String function;

	@org.kie.api.definition.type.Description(value = "Indistinta o Conjunta")
	private java.lang.String typeSignature;

	public AuthorizedData() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFunction() {
		return this.function;
	}

	public void setFunction(java.lang.String function) {
		this.function = function;
	}

	public java.lang.String getTypeSignature() {
		return this.typeSignature;
	}

	public void setTypeSignature(java.lang.String typeSignature) {
		this.typeSignature = typeSignature;
	}

	public AuthorizedData(java.lang.String name, java.lang.String role,
			java.lang.Long id, java.lang.String function,
			java.lang.String typeSignature) {
		this.name = name;
		this.role = role;
		this.id = id;
		this.function = function;
		this.typeSignature = typeSignature;
	}

}