package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuthorizedDataList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<com.facebank.enterprises.AuthorizedData> authorizedData;

	private java.lang.String typeSignature;

	public AuthorizedDataList() {
	}

	public java.util.List<com.facebank.enterprises.AuthorizedData> getAuthorizedData() {
		return this.authorizedData;
	}

	public void setAuthorizedData(
			java.util.List<com.facebank.enterprises.AuthorizedData> authorizedData) {
		this.authorizedData = authorizedData;
	}

	public java.lang.String getTypeSignature() {
		return this.typeSignature;
	}

	public void setTypeSignature(java.lang.String typeSignature) {
		this.typeSignature = typeSignature;
	}

	public AuthorizedDataList(
			java.util.List<com.facebank.enterprises.AuthorizedData> authorizedData,
			java.lang.String typeSignature) {
		this.authorizedData = authorizedData;
		this.typeSignature = typeSignature;
	}

}