package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AuthorizedData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	@org.kie.api.definition.type.Description("Indistinta o Conjunta")
	private java.lang.String signatureType;
	@org.kie.api.definition.type.Description("Operador o Admin")
	private java.lang.String role;

	@javax.persistence.Id
	@javax.persistence.GeneratedValue(generator = "AUTHORIZED_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.SequenceGenerator(sequenceName = "AUTHORIZED_ID_SEQ", name = "AUTHORIZED_ID_GENERATOR")
	private java.lang.Long id;

	public AuthorizedData() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSignatureType() {
		return this.signatureType;
	}

	public void setSignatureType(java.lang.String signatureType) {
		this.signatureType = signatureType;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public AuthorizedData(java.lang.String name,
			java.lang.String signatureType, java.lang.String role,
			java.lang.Long id) {
		this.name = name;
		this.signatureType = signatureType;
		this.role = role;
		this.id = id;
	}

}