package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AuthorizedData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String id;

	private java.lang.String rol;

	private java.lang.Integer number;

	private java.lang.String rolType;

	@javax.persistence.GeneratedValue(generator = "AUTHORIZEDDATA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "AUTHORIZEDDATA_ID_SEQ", name = "AUTHORIZEDDATA_ID_GENERATOR")
	private java.lang.Long idDatabase;

	private java.lang.String nameAuthorized;

	private java.lang.String functionAuthorized;

	private java.lang.String firstSurnameAuthorized;

	private java.lang.String secondSurnameAuthorized;

	public AuthorizedData() {
	}

	public java.lang.String getRol() {
		return this.rol;
	}

	public void setRol(java.lang.String rol) {
		this.rol = rol;
	}

	public java.lang.Integer getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.Integer number) {
		this.number = number;
	}

	public java.lang.String getRolType() {
		return this.rolType;
	}

	public void setRolType(java.lang.String rolType) {
		this.rolType = rolType;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Long getIdDatabase() {
		return this.idDatabase;
	}

	public void setIdDatabase(java.lang.Long idDatabase) {
		this.idDatabase = idDatabase;
	}

	public java.lang.String getNameAuthorized() {
		return this.nameAuthorized;
	}

	public void setNameAuthorized(java.lang.String nameAuthorized) {
		this.nameAuthorized = nameAuthorized;
	}

	public java.lang.String getFunctionAuthorized() {
		return this.functionAuthorized;
	}

	public void setFunctionAuthorized(java.lang.String functionAuthorized) {
		this.functionAuthorized = functionAuthorized;
	}

	public java.lang.String getFirstSurnameAuthorized() {
		return this.firstSurnameAuthorized;
	}

	public void setFirstSurnameAuthorized(
			java.lang.String firstSurnameAuthorized) {
		this.firstSurnameAuthorized = firstSurnameAuthorized;
	}

	public java.lang.String getSecondSurnameAuthorized() {
		return this.secondSurnameAuthorized;
	}

	public void setSecondSurnameAuthorized(
			java.lang.String secondSurnameAuthorized) {
		this.secondSurnameAuthorized = secondSurnameAuthorized;
	}

	public AuthorizedData(java.lang.String id, java.lang.String rol,
			java.lang.Integer number, java.lang.String rolType,
			java.lang.Long idDatabase, java.lang.String nameAuthorized,
			java.lang.String functionAuthorized,
			java.lang.String firstSurnameAuthorized,
			java.lang.String secondSurnameAuthorized) {
		this.id = id;
		this.rol = rol;
		this.number = number;
		this.rolType = rolType;
		this.idDatabase = idDatabase;
		this.nameAuthorized = nameAuthorized;
		this.functionAuthorized = functionAuthorized;
		this.firstSurnameAuthorized = firstSurnameAuthorized;
		this.secondSurnameAuthorized = secondSurnameAuthorized;
	}

}