package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AuthorizedData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	@javax.persistence.Id
	@javax.persistence.GeneratedValue(generator = "AUTHORIZED_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.SequenceGenerator(sequenceName = "AUTHORIZED_ID_SEQ", name = "AUTHORIZED_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String function;

	private java.lang.String rol;

	private java.lang.Integer number;

	private java.lang.String firstSurname;

	private java.lang.String secondSurname;

	public AuthorizedData() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFunction() {
		return this.function;
	}

	public void setFunction(java.lang.String function) {
		this.function = function;
	}

	public java.lang.String getRol() {
		return this.rol;
	}

	public void setRol(java.lang.String rol) {
		this.rol = rol;
	}

	public java.lang.Integer getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.Integer number) {
		this.number = number;
	}

	public java.lang.String getFirstSurname() {
		return this.firstSurname;
	}

	public void setFirstSurname(java.lang.String firstSurname) {
		this.firstSurname = firstSurname;
	}

	public java.lang.String getSecondSurname() {
		return this.secondSurname;
	}

	public void setSecondSurname(java.lang.String secondSurname) {
		this.secondSurname = secondSurname;
	}

	public AuthorizedData(java.lang.String name, java.lang.Long id,
			java.lang.String function, java.lang.String rol,
			java.lang.Integer number, java.lang.String firstSurname,
			java.lang.String secondSurname) {
		this.name = name;
		this.id = id;
		this.function = function;
		this.rol = rol;
		this.number = number;
		this.firstSurname = firstSurname;
		this.secondSurname = secondSurname;
	}

}