package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AutomaticDocumentsData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private AutomaticDocumentTypeData w8;
	private AutomaticDocumentTypeData w9;
	private AutomaticDocumentTypeData car;
	private AutomaticDocumentTypeData kyc;

	public AutomaticDocumentsData() {
	}

	public com.facebank.enterprises.AutomaticDocumentTypeData getW8() {
		return this.w8;
	}

	public void setW8(com.facebank.enterprises.AutomaticDocumentTypeData w8) {
		this.w8 = w8;
	}

	public com.facebank.enterprises.AutomaticDocumentTypeData getW9() {
		return this.w9;
	}

	public void setW9(com.facebank.enterprises.AutomaticDocumentTypeData w9) {
		this.w9 = w9;
	}

	public com.facebank.enterprises.AutomaticDocumentTypeData getCar() {
		return this.car;
	}

	public void setCar(com.facebank.enterprises.AutomaticDocumentTypeData car) {
		this.car = car;
	}

	public com.facebank.enterprises.AutomaticDocumentTypeData getKyc() {
		return this.kyc;
	}

	public void setKyc(com.facebank.enterprises.AutomaticDocumentTypeData kyc) {
		this.kyc = kyc;
	}

	public AutomaticDocumentsData(
			com.facebank.enterprises.AutomaticDocumentTypeData w8,
			com.facebank.enterprises.AutomaticDocumentTypeData w9,
			com.facebank.enterprises.AutomaticDocumentTypeData car,
			com.facebank.enterprises.AutomaticDocumentTypeData kyc) {
		this.w8 = w8;
		this.w9 = w9;
		this.car = car;
		this.kyc = kyc;
	}

}