package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BeneficiariesAndUploaderData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String nameUploader;
	private java.lang.String surnameUploader;
	private java.lang.String positionUploader;

	private java.lang.Boolean finalBeneficiaryFlag;

	private java.lang.String secondNameUploader;

	private java.lang.String secondSurnameUploader;

	private com.facebank.enterprises.FinalBeneficiaryDataList finalBeneficiaryDataList;

	public BeneficiariesAndUploaderData() {
	}

	public java.lang.String getNameUploader() {
		return this.nameUploader;
	}

	public void setNameUploader(java.lang.String nameUploader) {
		this.nameUploader = nameUploader;
	}

	public java.lang.String getSurnameUploader() {
		return this.surnameUploader;
	}

	public void setSurnameUploader(java.lang.String surnameUploader) {
		this.surnameUploader = surnameUploader;
	}

	public java.lang.String getPositionUploader() {
		return this.positionUploader;
	}

	public void setPositionUploader(java.lang.String positionUploader) {
		this.positionUploader = positionUploader;
	}

	public java.lang.Boolean getFinalBeneficiaryFlag() {
		return this.finalBeneficiaryFlag;
	}

	public void setFinalBeneficiaryFlag(java.lang.Boolean finalBeneficiaryFlag) {
		this.finalBeneficiaryFlag = finalBeneficiaryFlag;
	}

	public java.lang.String getSecondNameUploader() {
		return this.secondNameUploader;
	}

	public void setSecondNameUploader(java.lang.String secondNameUploader) {
		this.secondNameUploader = secondNameUploader;
	}

	public java.lang.String getSecondSurnameUploader() {
		return this.secondSurnameUploader;
	}

	public void setSecondSurnameUploader(java.lang.String secondSurnameUploader) {
		this.secondSurnameUploader = secondSurnameUploader;
	}

	public com.facebank.enterprises.FinalBeneficiaryDataList getFinalBeneficiaryDataList() {
		return this.finalBeneficiaryDataList;
	}

	public void setFinalBeneficiaryDataList(
			com.facebank.enterprises.FinalBeneficiaryDataList finalBeneficiaryDataList) {
		this.finalBeneficiaryDataList = finalBeneficiaryDataList;
	}

	public BeneficiariesAndUploaderData(
			java.lang.String nameUploader,
			java.lang.String surnameUploader,
			java.lang.String positionUploader,
			java.lang.Boolean finalBeneficiaryFlag,
			java.lang.String secondNameUploader,
			java.lang.String secondSurnameUploader,
			com.facebank.enterprises.FinalBeneficiaryDataList finalBeneficiaryDataList) {
		this.nameUploader = nameUploader;
		this.surnameUploader = surnameUploader;
		this.positionUploader = positionUploader;
		this.finalBeneficiaryFlag = finalBeneficiaryFlag;
		this.secondNameUploader = secondNameUploader;
		this.secondSurnameUploader = secondSurnameUploader;
		this.finalBeneficiaryDataList = finalBeneficiaryDataList;
	}

}