package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentTypeDataList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.DocumentTypeData> documentTypeData;

	public DocumentTypeDataList() {
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getDocumentTypeData() {
		return this.documentTypeData;
	}

	public void setDocumentTypeData(
			java.util.List<com.facebank.enterprises.DocumentTypeData> documentTypeData) {
		this.documentTypeData = documentTypeData;
	}

	public DocumentTypeDataList(
			java.util.List<com.facebank.enterprises.DocumentTypeData> documentTypeData) {
		this.documentTypeData = documentTypeData;
	}

}