package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentsData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String w8IndividualsEnglishId;

	private java.lang.String w8IndividualsSpanishId;

	private java.lang.String w9EnglishId;

	private java.lang.String w9SpanishId;

	private java.util.List<java.lang.String> financialDocumentsIds;

	private java.util.List<java.lang.String> legalDocumentsIds;

	private java.util.List<java.lang.String> generalDocumentsIds;

	public DocumentsData() {
	}

	public java.lang.String getW8IndividualsEnglishId() {
		return this.w8IndividualsEnglishId;
	}

	public void setW8IndividualsEnglishId(
			java.lang.String w8IndividualsEnglishId) {
		this.w8IndividualsEnglishId = w8IndividualsEnglishId;
	}

	public java.lang.String getW8IndividualsSpanishId() {
		return this.w8IndividualsSpanishId;
	}

	public void setW8IndividualsSpanishId(
			java.lang.String w8IndividualsSpanishId) {
		this.w8IndividualsSpanishId = w8IndividualsSpanishId;
	}

	public java.lang.String getW9EnglishId() {
		return this.w9EnglishId;
	}

	public void setW9EnglishId(java.lang.String w9EnglishId) {
		this.w9EnglishId = w9EnglishId;
	}

	public java.lang.String getW9SpanishId() {
		return this.w9SpanishId;
	}

	public void setW9SpanishId(java.lang.String w9SpanishId) {
		this.w9SpanishId = w9SpanishId;
	}

	public java.util.List<java.lang.String> getFinancialDocumentsIds() {
		return this.financialDocumentsIds;
	}

	public void setFinancialDocumentsIds(
			java.util.List<java.lang.String> financialDocumentsIds) {
		this.financialDocumentsIds = financialDocumentsIds;
	}

	public java.util.List<java.lang.String> getLegalDocumentsIds() {
		return this.legalDocumentsIds;
	}

	public void setLegalDocumentsIds(
			java.util.List<java.lang.String> legalDocumentsIds) {
		this.legalDocumentsIds = legalDocumentsIds;
	}

	public java.util.List<java.lang.String> getGeneralDocumentsIds() {
		return this.generalDocumentsIds;
	}

	public void setGeneralDocumentsIds(
			java.util.List<java.lang.String> generalDocumentsIds) {
		this.generalDocumentsIds = generalDocumentsIds;
	}

	public DocumentsData(java.lang.String w8IndividualsEnglishId,
			java.lang.String w8IndividualsSpanishId,
			java.lang.String w9EnglishId, java.lang.String w9SpanishId,
			java.util.List<java.lang.String> financialDocumentsIds,
			java.util.List<java.lang.String> legalDocumentsIds,
			java.util.List<java.lang.String> generalDocumentsIds) {
		this.w8IndividualsEnglishId = w8IndividualsEnglishId;
		this.w8IndividualsSpanishId = w8IndividualsSpanishId;
		this.w9EnglishId = w9EnglishId;
		this.w9SpanishId = w9SpanishId;
		this.financialDocumentsIds = financialDocumentsIds;
		this.legalDocumentsIds = legalDocumentsIds;
		this.generalDocumentsIds = generalDocumentsIds;
	}

}