package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentFoldersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String generalRequirementsId;
	private java.lang.String identificationsId;
	private java.lang.String aplicationsIds;

	private java.lang.String rootFolderId;

	public DocumentFoldersData() {
	}

	public java.lang.String getGeneralRequirementsId() {
		return this.generalRequirementsId;
	}

	public void setGeneralRequirementsId(java.lang.String generalRequirementsId) {
		this.generalRequirementsId = generalRequirementsId;
	}

	public java.lang.String getIdentificationsId() {
		return this.identificationsId;
	}

	public void setIdentificationsId(java.lang.String identificationsId) {
		this.identificationsId = identificationsId;
	}

	public java.lang.String getAplicationsIds() {
		return this.aplicationsIds;
	}

	public void setAplicationsIds(java.lang.String aplicationsIds) {
		this.aplicationsIds = aplicationsIds;
	}

	public java.lang.String getRootFolderId() {
		return this.rootFolderId;
	}

	public void setRootFolderId(java.lang.String rootFolderId) {
		this.rootFolderId = rootFolderId;
	}

	public DocumentFoldersData(java.lang.String generalRequirementsId,
			java.lang.String identificationsId,
			java.lang.String aplicationsIds, java.lang.String rootFolderId) {
		this.generalRequirementsId = generalRequirementsId;
		this.identificationsId = identificationsId;
		this.aplicationsIds = aplicationsIds;
		this.rootFolderId = rootFolderId;
	}

}