package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentsStockholdersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String passportId;

	private java.lang.String identificationId;

	private java.lang.String w8Id;

	public DocumentsStockholdersData() {
	}

	public java.lang.String getPassportId() {
		return this.passportId;
	}

	public void setPassportId(java.lang.String passportId) {
		this.passportId = passportId;
	}

	public java.lang.String getIdentificationId() {
		return this.identificationId;
	}

	public void setIdentificationId(java.lang.String identificationId) {
		this.identificationId = identificationId;
	}

	public java.lang.String getW8Id() {
		return this.w8Id;
	}

	public void setW8Id(java.lang.String w8Id) {
		this.w8Id = w8Id;
	}

	public DocumentsStockholdersData(java.lang.String passportId,
			java.lang.String identificationId, java.lang.String w8Id) {
		this.passportId = passportId;
		this.identificationId = identificationId;
		this.w8Id = w8Id;
	}

}