package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentsData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String w8IndividualsId;

	public DocumentsData() {
	}

	public java.lang.String getW8IndividualsId() {
		return this.w8IndividualsId;
	}

	public void setW8IndividualsId(java.lang.String w8IndividualsId) {
		this.w8IndividualsId = w8IndividualsId;
	}

	public DocumentsData(java.lang.String w8IndividualsId) {
		this.w8IndividualsId = w8IndividualsId;
	}

}