package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class EnterpriseData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "ENTERPRISEDATA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "ENTERPRISEDATA_ID_SEQ", name = "ENTERPRISEDATA_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String legalRepresentative;

	private java.lang.String enterpriseName;

	@org.kie.api.definition.type.Description("J - Persona Jurídica\nF - Persona Física")
	private java.lang.Character idType;

	private java.lang.Integer country;

	private java.lang.Integer businessType;

	private java.lang.Integer enterpriseType;

	@org.kie.api.definition.type.Description("Siglas")
	private java.lang.String acronym;

	private java.util.Date startDate;

	private java.lang.Integer accountMotive;

	private java.lang.Integer sourceOfFunds;

	public EnterpriseData() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getLegalRepresentative() {
		return this.legalRepresentative;
	}

	public void setLegalRepresentative(java.lang.String legalRepresentative) {
		this.legalRepresentative = legalRepresentative;
	}

	public java.lang.String getEnterpriseName() {
		return this.enterpriseName;
	}

	public void setEnterpriseName(java.lang.String enterpriseName) {
		this.enterpriseName = enterpriseName;
	}

	public java.lang.Character getIdType() {
		return this.idType;
	}

	public void setIdType(java.lang.Character idType) {
		this.idType = idType;
	}

	public java.lang.Integer getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.Integer country) {
		this.country = country;
	}

	public java.lang.Integer getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(java.lang.Integer businessType) {
		this.businessType = businessType;
	}

	public java.lang.Integer getEnterpriseType() {
		return this.enterpriseType;
	}

	public void setEnterpriseType(java.lang.Integer enterpriseType) {
		this.enterpriseType = enterpriseType;
	}

	public java.lang.String getAcronym() {
		return this.acronym;
	}

	public void setAcronym(java.lang.String acronym) {
		this.acronym = acronym;
	}

	public java.util.Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.util.Date startDate) {
		this.startDate = startDate;
	}

	public java.lang.Integer getAccountMotive() {
		return this.accountMotive;
	}

	public void setAccountMotive(java.lang.Integer accountMotive) {
		this.accountMotive = accountMotive;
	}

	public java.lang.Integer getSourceOfFunds() {
		return this.sourceOfFunds;
	}

	public void setSourceOfFunds(java.lang.Integer sourceOfFunds) {
		this.sourceOfFunds = sourceOfFunds;
	}

	public EnterpriseData(java.lang.Long id,
			java.lang.String legalRepresentative,
			java.lang.String enterpriseName, java.lang.Character idType,
			java.lang.Integer country, java.lang.Integer businessType,
			java.lang.Integer enterpriseType, java.lang.String acronym,
			java.util.Date startDate, java.lang.Integer accountMotive,
			java.lang.Integer sourceOfFunds) {
		this.id = id;
		this.legalRepresentative = legalRepresentative;
		this.enterpriseName = enterpriseName;
		this.idType = idType;
		this.country = country;
		this.businessType = businessType;
		this.enterpriseType = enterpriseType;
		this.acronym = acronym;
		this.startDate = startDate;
		this.accountMotive = accountMotive;
		this.sourceOfFunds = sourceOfFunds;
	}

}