package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FinalBeneficiaryData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idStockholderRelated;

	private java.lang.String nameBeneficiary;

	private java.lang.Double participationBeneficiary;

	private java.lang.String secondSurNameBeneficiary;

	private java.lang.String surNameBeneficiary;

	private java.lang.String typeBeneficiary;

	private java.lang.String idBeneficiary;

	private java.lang.String secondNameBeneficiary;

	private java.lang.String birthDateBeneficiary;

	private java.lang.String emailBeneficiary;

	private java.lang.String addressBeneficiary;

	private java.lang.String cityBeneficiary;

	private java.lang.String stateBeneficiary;

	private java.lang.String countryBeneficiary;

	private java.lang.String issuingCountryBeneficiary;

	private java.lang.String idNumberBeneficiary;

	private java.lang.String stateBeneficiaryValue;

	private java.lang.String issuingCountryBeneficiaryValue;

	private java.lang.String companyNameBeneficiary;

	private java.lang.String signatoryBeneficiary;

	private java.lang.String cityBeneficiaryValue;

	private java.lang.String countryBeneficiaryValue;

	public FinalBeneficiaryData() {
	}

	public java.lang.String getIdStockholderRelated() {
		return this.idStockholderRelated;
	}

	public void setIdStockholderRelated(java.lang.String idStockholderRelated) {
		this.idStockholderRelated = idStockholderRelated;
	}

	public java.lang.String getNameBeneficiary() {
		return this.nameBeneficiary;
	}

	public void setNameBeneficiary(java.lang.String nameBeneficiary) {
		this.nameBeneficiary = nameBeneficiary;
	}

	public java.lang.Double getParticipationBeneficiary() {
		return this.participationBeneficiary;
	}

	public void setParticipationBeneficiary(
			java.lang.Double participationBeneficiary) {
		this.participationBeneficiary = participationBeneficiary;
	}

	public java.lang.String getSecondSurNameBeneficiary() {
		return this.secondSurNameBeneficiary;
	}

	public void setSecondSurNameBeneficiary(
			java.lang.String secondSurNameBeneficiary) {
		this.secondSurNameBeneficiary = secondSurNameBeneficiary;
	}

	public java.lang.String getSurNameBeneficiary() {
		return this.surNameBeneficiary;
	}

	public void setSurNameBeneficiary(java.lang.String surNameBeneficiary) {
		this.surNameBeneficiary = surNameBeneficiary;
	}

	public java.lang.String getTypeBeneficiary() {
		return this.typeBeneficiary;
	}

	public void setTypeBeneficiary(java.lang.String typeBeneficiary) {
		this.typeBeneficiary = typeBeneficiary;
	}

	public java.lang.String getIdBeneficiary() {
		return this.idBeneficiary;
	}

	public void setIdBeneficiary(java.lang.String idBeneficiary) {
		this.idBeneficiary = idBeneficiary;
	}

	public java.lang.String getSecondNameBeneficiary() {
		return this.secondNameBeneficiary;
	}

	public void setSecondNameBeneficiary(java.lang.String secondNameBeneficiary) {
		this.secondNameBeneficiary = secondNameBeneficiary;
	}

	public java.lang.String getBirthDateBeneficiary() {
		return this.birthDateBeneficiary;
	}

	public void setBirthDateBeneficiary(java.lang.String birthDateBeneficiary) {
		this.birthDateBeneficiary = birthDateBeneficiary;
	}

	public java.lang.String getEmailBeneficiary() {
		return this.emailBeneficiary;
	}

	public void setEmailBeneficiary(java.lang.String emailBeneficiary) {
		this.emailBeneficiary = emailBeneficiary;
	}

	public java.lang.String getAddressBeneficiary() {
		return this.addressBeneficiary;
	}

	public void setAddressBeneficiary(java.lang.String addressBeneficiary) {
		this.addressBeneficiary = addressBeneficiary;
	}

	public java.lang.String getCityBeneficiary() {
		return this.cityBeneficiary;
	}

	public void setCityBeneficiary(java.lang.String cityBeneficiary) {
		this.cityBeneficiary = cityBeneficiary;
	}

	public java.lang.String getStateBeneficiary() {
		return this.stateBeneficiary;
	}

	public void setStateBeneficiary(java.lang.String stateBeneficiary) {
		this.stateBeneficiary = stateBeneficiary;
	}

	public java.lang.String getCountryBeneficiary() {
		return this.countryBeneficiary;
	}

	public void setCountryBeneficiary(java.lang.String countryBeneficiary) {
		this.countryBeneficiary = countryBeneficiary;
	}

	public java.lang.String getIssuingCountryBeneficiary() {
		return this.issuingCountryBeneficiary;
	}

	public void setIssuingCountryBeneficiary(
			java.lang.String issuingCountryBeneficiary) {
		this.issuingCountryBeneficiary = issuingCountryBeneficiary;
	}

	public java.lang.String getIdNumberBeneficiary() {
		return this.idNumberBeneficiary;
	}

	public void setIdNumberBeneficiary(java.lang.String idNumberBeneficiary) {
		this.idNumberBeneficiary = idNumberBeneficiary;
	}

	public java.lang.String getStateBeneficiaryValue() {
		return this.stateBeneficiaryValue;
	}

	public void setStateBeneficiaryValue(java.lang.String stateBeneficiaryValue) {
		this.stateBeneficiaryValue = stateBeneficiaryValue;
	}

	public java.lang.String getIssuingCountryBeneficiaryValue() {
		return this.issuingCountryBeneficiaryValue;
	}

	public void setIssuingCountryBeneficiaryValue(
			java.lang.String issuingCountryBeneficiaryValue) {
		this.issuingCountryBeneficiaryValue = issuingCountryBeneficiaryValue;
	}

	public java.lang.String getCompanyNameBeneficiary() {
		return this.companyNameBeneficiary;
	}

	public void setCompanyNameBeneficiary(
			java.lang.String companyNameBeneficiary) {
		this.companyNameBeneficiary = companyNameBeneficiary;
	}

	public java.lang.String getSignatoryBeneficiary() {
		return this.signatoryBeneficiary;
	}

	public void setSignatoryBeneficiary(java.lang.String signatoryBeneficiary) {
		this.signatoryBeneficiary = signatoryBeneficiary;
	}

	public java.lang.String getCityBeneficiaryValue() {
		return this.cityBeneficiaryValue;
	}

	public void setCityBeneficiaryValue(java.lang.String cityBeneficiaryValue) {
		this.cityBeneficiaryValue = cityBeneficiaryValue;
	}

	public java.lang.String getCountryBeneficiaryValue() {
		return this.countryBeneficiaryValue;
	}

	public void setCountryBeneficiaryValue(
			java.lang.String countryBeneficiaryValue) {
		this.countryBeneficiaryValue = countryBeneficiaryValue;
	}

	public FinalBeneficiaryData(java.lang.String idStockholderRelated,
			java.lang.String nameBeneficiary,
			java.lang.Double participationBeneficiary,
			java.lang.String secondSurNameBeneficiary,
			java.lang.String surNameBeneficiary,
			java.lang.String typeBeneficiary, java.lang.String idBeneficiary,
			java.lang.String secondNameBeneficiary,
			java.lang.String birthDateBeneficiary,
			java.lang.String emailBeneficiary,
			java.lang.String addressBeneficiary,
			java.lang.String cityBeneficiary,
			java.lang.String stateBeneficiary,
			java.lang.String countryBeneficiary,
			java.lang.String issuingCountryBeneficiary,
			java.lang.String idNumberBeneficiary,
			java.lang.String stateBeneficiaryValue,
			java.lang.String issuingCountryBeneficiaryValue,
			java.lang.String companyNameBeneficiary,
			java.lang.String signatoryBeneficiary,
			java.lang.String cityBeneficiaryValue,
			java.lang.String countryBeneficiaryValue) {
		this.idStockholderRelated = idStockholderRelated;
		this.nameBeneficiary = nameBeneficiary;
		this.participationBeneficiary = participationBeneficiary;
		this.secondSurNameBeneficiary = secondSurNameBeneficiary;
		this.surNameBeneficiary = surNameBeneficiary;
		this.typeBeneficiary = typeBeneficiary;
		this.idBeneficiary = idBeneficiary;
		this.secondNameBeneficiary = secondNameBeneficiary;
		this.birthDateBeneficiary = birthDateBeneficiary;
		this.emailBeneficiary = emailBeneficiary;
		this.addressBeneficiary = addressBeneficiary;
		this.cityBeneficiary = cityBeneficiary;
		this.stateBeneficiary = stateBeneficiary;
		this.countryBeneficiary = countryBeneficiary;
		this.issuingCountryBeneficiary = issuingCountryBeneficiary;
		this.idNumberBeneficiary = idNumberBeneficiary;
		this.stateBeneficiaryValue = stateBeneficiaryValue;
		this.issuingCountryBeneficiaryValue = issuingCountryBeneficiaryValue;
		this.companyNameBeneficiary = companyNameBeneficiary;
		this.signatoryBeneficiary = signatoryBeneficiary;
		this.cityBeneficiaryValue = cityBeneficiaryValue;
		this.countryBeneficiaryValue = countryBeneficiaryValue;
	}

}