package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FinancialDocumentsData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private DocumentTypeDataList taxReturn;
	private DocumentTypeDataList financialStatements;
	private DocumentTypeDataList bankReferences;

	public FinancialDocumentsData() {
	}

	public com.facebank.enterprises.DocumentTypeDataList getTaxReturn() {
		return this.taxReturn;
	}

	public void setTaxReturn(
			com.facebank.enterprises.DocumentTypeDataList taxReturn) {
		this.taxReturn = taxReturn;
	}

	public com.facebank.enterprises.DocumentTypeDataList getFinancialStatements() {
		return this.financialStatements;
	}

	public void setFinancialStatements(
			com.facebank.enterprises.DocumentTypeDataList financialStatements) {
		this.financialStatements = financialStatements;
	}

	public com.facebank.enterprises.DocumentTypeDataList getBankReferences() {
		return this.bankReferences;
	}

	public void setBankReferences(
			com.facebank.enterprises.DocumentTypeDataList bankReferences) {
		this.bankReferences = bankReferences;
	}

	public FinancialDocumentsData(
			com.facebank.enterprises.DocumentTypeDataList taxReturn,
			com.facebank.enterprises.DocumentTypeDataList financialStatements,
			com.facebank.enterprises.DocumentTypeDataList bankReferences) {
		this.taxReturn = taxReturn;
		this.financialStatements = financialStatements;
		this.bankReferences = bankReferences;
	}

}