package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FinalBeneficiaryDataList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.FinalBeneficiaryData> finalBeneficiaryData;

	public FinalBeneficiaryDataList() {
	}

	public java.util.List<com.facebank.enterprises.FinalBeneficiaryData> getFinalBeneficiaryData() {
		return this.finalBeneficiaryData;
	}

	public void setFinalBeneficiaryData(
			java.util.List<com.facebank.enterprises.FinalBeneficiaryData> finalBeneficiaryData) {
		this.finalBeneficiaryData = finalBeneficiaryData;
	}

	public FinalBeneficiaryDataList(
			java.util.List<com.facebank.enterprises.FinalBeneficiaryData> finalBeneficiaryData) {
		this.finalBeneficiaryData = finalBeneficiaryData;
	}

}