package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class HeaderData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.Id
	@javax.persistence.GeneratedValue(generator = "HEADERDATA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.SequenceGenerator(sequenceName = "HEADERDATA_ID_SEQ", name = "HEADERDATA_ID_GENERATOR")
	private java.lang.Long id;
	private java.lang.String bdfLogin;
	private java.lang.String bdfName;

	private java.lang.String clientName;

	public HeaderData() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getBdfLogin() {
		return this.bdfLogin;
	}

	public void setBdfLogin(java.lang.String bdfLogin) {
		this.bdfLogin = bdfLogin;
	}

	public java.lang.String getBdfName() {
		return this.bdfName;
	}

	public void setBdfName(java.lang.String bdfName) {
		this.bdfName = bdfName;
	}

	public java.lang.String getClientName() {
		return this.clientName;
	}

	public void setClientName(java.lang.String clientName) {
		this.clientName = clientName;
	}

	public HeaderData(java.lang.Long id, java.lang.String bdfLogin,
			java.lang.String bdfName, java.lang.String clientName) {
		this.id = id;
		this.bdfLogin = bdfLogin;
		this.bdfName = bdfName;
		this.clientName = clientName;
	}

}