package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReceiverData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String nameReceiver;

	private java.lang.String relationshipReceiver;

	private java.lang.String id;

	private java.lang.String number;

	private java.lang.Boolean flagCorrection;

	private java.lang.Boolean flagAlertCorrection;

	private java.lang.Boolean flagDisableDelete;

	private java.lang.Boolean flagDisableEdit;

	public ReceiverData() {
	}

	public java.lang.String getNameReceiver() {
		return this.nameReceiver;
	}

	public void setNameReceiver(java.lang.String nameReceiver) {
		this.nameReceiver = nameReceiver;
	}

	public java.lang.String getRelationshipReceiver() {
		return this.relationshipReceiver;
	}

	public void setRelationshipReceiver(java.lang.String relationshipReceiver) {
		this.relationshipReceiver = relationshipReceiver;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.String number) {
		this.number = number;
	}

	public java.lang.Boolean getFlagCorrection() {
		return this.flagCorrection;
	}

	public void setFlagCorrection(java.lang.Boolean flagCorrection) {
		this.flagCorrection = flagCorrection;
	}

	public java.lang.Boolean getFlagAlertCorrection() {
		return this.flagAlertCorrection;
	}

	public void setFlagAlertCorrection(java.lang.Boolean flagAlertCorrection) {
		this.flagAlertCorrection = flagAlertCorrection;
	}

	public java.lang.Boolean getFlagDisableDelete() {
		return this.flagDisableDelete;
	}

	public void setFlagDisableDelete(java.lang.Boolean flagDisableDelete) {
		this.flagDisableDelete = flagDisableDelete;
	}

	public java.lang.Boolean getFlagDisableEdit() {
		return this.flagDisableEdit;
	}

	public void setFlagDisableEdit(java.lang.Boolean flagDisableEdit) {
		this.flagDisableEdit = flagDisableEdit;
	}

	public ReceiverData(java.lang.String nameReceiver,
			java.lang.String relationshipReceiver, java.lang.String id,
			java.lang.String number, java.lang.Boolean flagCorrection,
			java.lang.Boolean flagAlertCorrection,
			java.lang.Boolean flagDisableDelete,
			java.lang.Boolean flagDisableEdit) {
		this.nameReceiver = nameReceiver;
		this.relationshipReceiver = relationshipReceiver;
		this.id = id;
		this.number = number;
		this.flagCorrection = flagCorrection;
		this.flagAlertCorrection = flagAlertCorrection;
		this.flagDisableDelete = flagDisableDelete;
		this.flagDisableEdit = flagDisableEdit;
	}

}