package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SenderData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String nameSender;

	private java.lang.String relationshipSender;

	private java.lang.String id;

	public SenderData() {
	}

	public java.lang.String getNameSender() {
		return this.nameSender;
	}

	public void setNameSender(java.lang.String nameSender) {
		this.nameSender = nameSender;
	}

	public java.lang.String getRelationshipSender() {
		return this.relationshipSender;
	}

	public void setRelationshipSender(java.lang.String relationshipSender) {
		this.relationshipSender = relationshipSender;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public SenderData(java.lang.String nameSender,
			java.lang.String relationshipSender, java.lang.String id) {
		this.nameSender = nameSender;
		this.relationshipSender = relationshipSender;
		this.id = id;
	}

}