package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SenderData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String relationship;

	public SenderData() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(java.lang.String relationship) {
		this.relationship = relationship;
	}

	public SenderData(java.lang.String name, java.lang.String relationship) {
		this.name = name;
		this.relationship = relationship;
	}

}