package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ShareholdersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "SHAREHOLDERSDATA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "SHAREHOLDERSDATA_ID_SEQ", name = "SHAREHOLDERSDATA_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String name;

	private java.lang.String title;

	private java.lang.String entityType;

	private java.lang.Double participationPercentage;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private com.facebank.enterprises.ShareholdersDataList subShareholdersDataList;

	private java.lang.String nationality;

	private java.lang.Integer number;

	public ShareholdersData() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(java.lang.String entityType) {
		this.entityType = entityType;
	}

	public java.lang.Double getParticipationPercentage() {
		return this.participationPercentage;
	}

	public void setParticipationPercentage(
			java.lang.Double participationPercentage) {
		this.participationPercentage = participationPercentage;
	}

	public com.facebank.enterprises.ShareholdersDataList getSubShareholdersDataList() {
		return this.subShareholdersDataList;
	}

	public void setSubShareholdersDataList(
			com.facebank.enterprises.ShareholdersDataList subShareholdersDataList) {
		this.subShareholdersDataList = subShareholdersDataList;
	}

	public java.lang.String getNationality() {
		return this.nationality;
	}

	public void setNationality(java.lang.String nationality) {
		this.nationality = nationality;
	}

	public java.lang.Integer getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.Integer number) {
		this.number = number;
	}

	public ShareholdersData(
			java.lang.Long id,
			java.lang.String name,
			java.lang.String title,
			java.lang.String entityType,
			java.lang.Double participationPercentage,
			com.facebank.enterprises.ShareholdersDataList subShareholdersDataList,
			java.lang.String nationality, java.lang.Integer number) {
		this.id = id;
		this.name = name;
		this.title = title;
		this.entityType = entityType;
		this.participationPercentage = participationPercentage;
		this.subShareholdersDataList = subShareholdersDataList;
		this.nationality = nationality;
		this.number = number;
	}

}