package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ShareholdersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "SHAREHOLDERSDATA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "SHAREHOLDERSDATA_ID_SEQ", name = "SHAREHOLDERSDATA_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String name;

	private java.lang.String title;

	private java.lang.String nationality;

	private java.lang.Integer number;

	private java.lang.String type;

	private java.lang.Double participation;

	public ShareholdersData() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getNationality() {
		return this.nationality;
	}

	public void setNationality(java.lang.String nationality) {
		this.nationality = nationality;
	}

	public java.lang.Integer getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.Integer number) {
		this.number = number;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Double getParticipation() {
		return this.participation;
	}

	public void setParticipation(java.lang.Double participation) {
		this.participation = participation;
	}

	public ShareholdersData(java.lang.Long id, java.lang.String name,
			java.lang.String title, java.lang.String nationality,
			java.lang.Integer number, java.lang.String type,
			java.lang.Double participation) {
		this.id = id;
		this.name = name;
		this.title = title;
		this.nationality = nationality;
		this.number = number;
		this.type = type;
		this.participation = participation;
	}

}