package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholdersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.String nationality;

	private java.lang.Integer number;

	private java.lang.String type;

	private java.lang.Double participation;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private com.facebank.enterprises.StockholdersDataList subStockholders;

	private java.lang.String signatory;

	private java.lang.String surName;

	private java.lang.String secondSurName;

	private java.lang.String position;

	public StockholdersData() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getNationality() {
		return this.nationality;
	}

	public void setNationality(java.lang.String nationality) {
		this.nationality = nationality;
	}

	public java.lang.Integer getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.Integer number) {
		this.number = number;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Double getParticipation() {
		return this.participation;
	}

	public void setParticipation(java.lang.Double participation) {
		this.participation = participation;
	}

	public com.facebank.enterprises.StockholdersDataList getSubStockholders() {
		return this.subStockholders;
	}

	public void setSubStockholders(
			com.facebank.enterprises.StockholdersDataList subStockholders) {
		this.subStockholders = subStockholders;
	}

	public java.lang.String getSignatory() {
		return this.signatory;
	}

	public void setSignatory(java.lang.String signatory) {
		this.signatory = signatory;
	}

	public java.lang.String getSurName() {
		return this.surName;
	}

	public void setSurName(java.lang.String surName) {
		this.surName = surName;
	}

	public java.lang.String getSecondSurName() {
		return this.secondSurName;
	}

	public void setSecondSurName(java.lang.String secondSurName) {
		this.secondSurName = secondSurName;
	}

	public java.lang.String getPosition() {
		return this.position;
	}

	public void setPosition(java.lang.String position) {
		this.position = position;
	}

	public StockholdersData(java.lang.String name,
			java.lang.String nationality, java.lang.Integer number,
			java.lang.String type, java.lang.Double participation,
			com.facebank.enterprises.StockholdersDataList subStockholders,
			java.lang.String signatory, java.lang.String surName,
			java.lang.String secondSurName, java.lang.String position) {
		this.name = name;
		this.nationality = nationality;
		this.number = number;
		this.type = type;
		this.participation = participation;
		this.subStockholders = subStockholders;
		this.signatory = signatory;
		this.surName = surName;
		this.secondSurName = secondSurName;
		this.position = position;
	}

}