package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderCompanyGeneralDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.DocumentTypeData> evidence;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> w8;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> w9;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> identifications;

	public StockholderCompanyGeneralDocumentsData() {
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getEvidence() {
		return this.evidence;
	}

	public void setEvidence(
			java.util.List<com.facebank.enterprises.DocumentTypeData> evidence) {
		this.evidence = evidence;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getW8() {
		return this.w8;
	}

	public void setW8(
			java.util.List<com.facebank.enterprises.DocumentTypeData> w8) {
		this.w8 = w8;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getW9() {
		return this.w9;
	}

	public void setW9(
			java.util.List<com.facebank.enterprises.DocumentTypeData> w9) {
		this.w9 = w9;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getIdentifications() {
		return this.identifications;
	}

	public void setIdentifications(
			java.util.List<com.facebank.enterprises.DocumentTypeData> identifications) {
		this.identifications = identifications;
	}

	public StockholderCompanyGeneralDocumentsData(
			java.util.List<com.facebank.enterprises.DocumentTypeData> evidence,
			java.util.List<com.facebank.enterprises.DocumentTypeData> w8,
			java.util.List<com.facebank.enterprises.DocumentTypeData> w9,
			java.util.List<com.facebank.enterprises.DocumentTypeData> identifications) {
		this.evidence = evidence;
		this.w8 = w8;
		this.w9 = w9;
		this.identifications = identifications;
	}

}