package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderPersonIdentificationDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private DocumentTypeDataList personIdentifications;

	public StockholderPersonIdentificationDocumentsData() {
	}

	public com.facebank.enterprises.DocumentTypeDataList getPersonIdentifications() {
		return this.personIdentifications;
	}

	public void setPersonIdentifications(
			com.facebank.enterprises.DocumentTypeDataList personIdentifications) {
		this.personIdentifications = personIdentifications;
	}

	public StockholderPersonIdentificationDocumentsData(
			com.facebank.enterprises.DocumentTypeDataList personIdentifications) {
		this.personIdentifications = personIdentifications;
	}

}