package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderCompanyLegalDocumentsData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public StockholderCompanyLegalDocumentsData() {
    }




}