package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderPersonGeneralDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.DocumentTypeData> w8;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> w9;
	private com.facebank.enterprises.DocumentTypeData evidence;

	public StockholderPersonGeneralDocumentsData() {
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getW8() {
		return this.w8;
	}

	public void setW8(
			java.util.List<com.facebank.enterprises.DocumentTypeData> w8) {
		this.w8 = w8;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getW9() {
		return this.w9;
	}

	public void setW9(
			java.util.List<com.facebank.enterprises.DocumentTypeData> w9) {
		this.w9 = w9;
	}

	public com.facebank.enterprises.DocumentTypeData getEvidence() {
		return this.evidence;
	}

	public void setEvidence(com.facebank.enterprises.DocumentTypeData evidence) {
		this.evidence = evidence;
	}

	public StockholderPersonGeneralDocumentsData(
			java.util.List<com.facebank.enterprises.DocumentTypeData> w8,
			java.util.List<com.facebank.enterprises.DocumentTypeData> w9,
			com.facebank.enterprises.DocumentTypeData evidence) {
		this.w8 = w8;
		this.w9 = w9;
		this.evidence = evidence;
	}

}