package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderPersonFinancialDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.DocumentTypeData> bankReference;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> workLetter;

	public StockholderPersonFinancialDocumentsData() {
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getBankReference() {
		return this.bankReference;
	}

	public void setBankReference(
			java.util.List<com.facebank.enterprises.DocumentTypeData> bankReference) {
		this.bankReference = bankReference;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getWorkLetter() {
		return this.workLetter;
	}

	public void setWorkLetter(
			java.util.List<com.facebank.enterprises.DocumentTypeData> workLetter) {
		this.workLetter = workLetter;
	}

	public StockholderPersonFinancialDocumentsData(
			java.util.List<com.facebank.enterprises.DocumentTypeData> bankReference,
			java.util.List<com.facebank.enterprises.DocumentTypeData> workLetter) {
		this.bankReference = bankReference;
		this.workLetter = workLetter;
	}

}