package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderCompanyFinancialDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private DocumentTypeDataList bankReferences;
	private DocumentTypeDataList financialStatements;
	private DocumentTypeDataList taxReturn;
	private DocumentTypeDataList projectedCashFlow;
	private DocumentTypeDataList businessProjection;

	public StockholderCompanyFinancialDocumentsData() {
	}

	public com.facebank.enterprises.DocumentTypeDataList getBankReferences() {
		return this.bankReferences;
	}

	public void setBankReferences(
			com.facebank.enterprises.DocumentTypeDataList bankReferences) {
		this.bankReferences = bankReferences;
	}

	public com.facebank.enterprises.DocumentTypeDataList getFinancialStatements() {
		return this.financialStatements;
	}

	public void setFinancialStatements(
			com.facebank.enterprises.DocumentTypeDataList financialStatements) {
		this.financialStatements = financialStatements;
	}

	public com.facebank.enterprises.DocumentTypeDataList getTaxReturn() {
		return this.taxReturn;
	}

	public void setTaxReturn(
			com.facebank.enterprises.DocumentTypeDataList taxReturn) {
		this.taxReturn = taxReturn;
	}

	public com.facebank.enterprises.DocumentTypeDataList getProjectedCashFlow() {
		return this.projectedCashFlow;
	}

	public void setProjectedCashFlow(
			com.facebank.enterprises.DocumentTypeDataList projectedCashFlow) {
		this.projectedCashFlow = projectedCashFlow;
	}

	public com.facebank.enterprises.DocumentTypeDataList getBusinessProjection() {
		return this.businessProjection;
	}

	public void setBusinessProjection(
			com.facebank.enterprises.DocumentTypeDataList businessProjection) {
		this.businessProjection = businessProjection;
	}

	public StockholderCompanyFinancialDocumentsData(
			com.facebank.enterprises.DocumentTypeDataList bankReferences,
			com.facebank.enterprises.DocumentTypeDataList financialStatements,
			com.facebank.enterprises.DocumentTypeDataList taxReturn,
			com.facebank.enterprises.DocumentTypeDataList projectedCashFlow,
			com.facebank.enterprises.DocumentTypeDataList businessProjection) {
		this.bankReferences = bankReferences;
		this.financialStatements = financialStatements;
		this.taxReturn = taxReturn;
		this.projectedCashFlow = projectedCashFlow;
		this.businessProjection = businessProjection;
	}

}