package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderPersonIdentificationDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.DocumentTypeData> personIdentifications;

	public StockholderPersonIdentificationDocumentsData() {
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getPersonIdentifications() {
		return this.personIdentifications;
	}

	public void setPersonIdentifications(
			java.util.List<com.facebank.enterprises.DocumentTypeData> personIdentifications) {
		this.personIdentifications = personIdentifications;
	}

	public StockholderPersonIdentificationDocumentsData(
			java.util.List<com.facebank.enterprises.DocumentTypeData> personIdentifications) {
		this.personIdentifications = personIdentifications;
	}

}