package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderPersonGeneralDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private DocumentTypeDataList w8;
	private DocumentTypeDataList w9;
	private DocumentTypeDataList evidence;

	public StockholderPersonGeneralDocumentsData() {
	}

	public com.facebank.enterprises.DocumentTypeDataList getW8() {
		return this.w8;
	}

	public void setW8(com.facebank.enterprises.DocumentTypeDataList w8) {
		this.w8 = w8;
	}

	public com.facebank.enterprises.DocumentTypeDataList getW9() {
		return this.w9;
	}

	public void setW9(com.facebank.enterprises.DocumentTypeDataList w9) {
		this.w9 = w9;
	}

	public com.facebank.enterprises.DocumentTypeDataList getEvidence() {
		return this.evidence;
	}

	public void setEvidence(
			com.facebank.enterprises.DocumentTypeDataList evidence) {
		this.evidence = evidence;
	}

	public StockholderPersonGeneralDocumentsData(
			com.facebank.enterprises.DocumentTypeDataList w8,
			com.facebank.enterprises.DocumentTypeDataList w9,
			com.facebank.enterprises.DocumentTypeDataList evidence) {
		this.w8 = w8;
		this.w9 = w9;
		this.evidence = evidence;
	}

}