package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderPersonFinancialDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private DocumentTypeDataList bankReference;
	private DocumentTypeDataList workLetter;

	public StockholderPersonFinancialDocumentsData() {
	}

	public com.facebank.enterprises.DocumentTypeDataList getBankReference() {
		return this.bankReference;
	}

	public void setBankReference(
			com.facebank.enterprises.DocumentTypeDataList bankReference) {
		this.bankReference = bankReference;
	}

	public com.facebank.enterprises.DocumentTypeDataList getWorkLetter() {
		return this.workLetter;
	}

	public void setWorkLetter(
			com.facebank.enterprises.DocumentTypeDataList workLetter) {
		this.workLetter = workLetter;
	}

	public StockholderPersonFinancialDocumentsData(
			com.facebank.enterprises.DocumentTypeDataList bankReference,
			com.facebank.enterprises.DocumentTypeDataList workLetter) {
		this.bankReference = bankReference;
		this.workLetter = workLetter;
	}

}