package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholdersDataList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.StockholdersData> stockholdersData;

	public StockholdersDataList() {
	}

	public java.util.List<com.facebank.enterprises.StockholdersData> getStockholdersData() {
		return this.stockholdersData;
	}

	public void setStockholdersData(
			java.util.List<com.facebank.enterprises.StockholdersData> stockholdersData) {
		this.stockholdersData = stockholdersData;
	}

	public StockholdersDataList(
			java.util.List<com.facebank.enterprises.StockholdersData> stockholdersData) {
		this.stockholdersData = stockholdersData;
	}

}