package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderPersonGeneralDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private DocumentTypeDataList evidence;

	private com.facebank.enterprises.DocumentTypeDataList w8_w9;

	public StockholderPersonGeneralDocumentsData() {
	}

	public com.facebank.enterprises.DocumentTypeDataList getEvidence() {
		return this.evidence;
	}

	public void setEvidence(
			com.facebank.enterprises.DocumentTypeDataList evidence) {
		this.evidence = evidence;
	}

	public com.facebank.enterprises.DocumentTypeDataList getW8_w9() {
		return this.w8_w9;
	}

	public void setW8_w9(com.facebank.enterprises.DocumentTypeDataList w8_w9) {
		this.w8_w9 = w8_w9;
	}

	public StockholderPersonGeneralDocumentsData(
			com.facebank.enterprises.DocumentTypeDataList evidence,
			com.facebank.enterprises.DocumentTypeDataList w8_w9) {
		this.evidence = evidence;
		this.w8_w9 = w8_w9;
	}

}