package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderDocumentsData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private StockholderPersonGeneralDocumentsData stockholderPersonGeneralDocuments;

	private StockholderPersonFinancialDocumentsData stockholderPersonFinancialDocuments;

	private StockholderCompanyGeneralDocumentsData stockholderCompanyGeneralDocuments;

	private StockholderCompanyFinancialDocumentsData stockholderCompanyFinancialDocuments;

	private String type;

	private String idStockholder;

	private String nameStockholder;

	private StockholderCompanyLegalDocumentsData stockholderCompanyLegalDocuments;

	private StockholderPersonIdentificationDocumentsData identifications;

	private java.lang.String nationalityStockholder;

	public StockholderDocumentsData() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getIdStockholder() {
		return this.idStockholder;
	}

	public void setIdStockholder(java.lang.String idStockholder) {
		this.idStockholder = idStockholder;
	}

	public java.lang.String getNameStockholder() {
		return this.nameStockholder;
	}

	public void setNameStockholder(java.lang.String nameStockholder) {
		this.nameStockholder = nameStockholder;
	}

	public com.facebank.enterprises.StockholderPersonGeneralDocumentsData getStockholderPersonGeneralDocuments() {
		return this.stockholderPersonGeneralDocuments;
	}

	public void setStockholderPersonGeneralDocuments(
			com.facebank.enterprises.StockholderPersonGeneralDocumentsData stockholderPersonGeneralDocuments) {
		this.stockholderPersonGeneralDocuments = stockholderPersonGeneralDocuments;
	}

	public com.facebank.enterprises.StockholderPersonFinancialDocumentsData getStockholderPersonFinancialDocuments() {
		return this.stockholderPersonFinancialDocuments;
	}

	public void setStockholderPersonFinancialDocuments(
			com.facebank.enterprises.StockholderPersonFinancialDocumentsData stockholderPersonFinancialDocuments) {
		this.stockholderPersonFinancialDocuments = stockholderPersonFinancialDocuments;
	}

	public com.facebank.enterprises.StockholderCompanyGeneralDocumentsData getStockholderCompanyGeneralDocuments() {
		return this.stockholderCompanyGeneralDocuments;
	}

	public void setStockholderCompanyGeneralDocuments(
			com.facebank.enterprises.StockholderCompanyGeneralDocumentsData stockholderCompanyGeneralDocuments) {
		this.stockholderCompanyGeneralDocuments = stockholderCompanyGeneralDocuments;
	}

	public com.facebank.enterprises.StockholderCompanyFinancialDocumentsData getStockholderCompanyFinancialDocuments() {
		return this.stockholderCompanyFinancialDocuments;
	}

	public void setStockholderCompanyFinancialDocuments(
			com.facebank.enterprises.StockholderCompanyFinancialDocumentsData stockholderCompanyFinancialDocuments) {
		this.stockholderCompanyFinancialDocuments = stockholderCompanyFinancialDocuments;
	}

	public com.facebank.enterprises.StockholderCompanyLegalDocumentsData getStockholderCompanyLegalDocuments() {
		return this.stockholderCompanyLegalDocuments;
	}

	public void setStockholderCompanyLegalDocuments(
			com.facebank.enterprises.StockholderCompanyLegalDocumentsData stockholderCompanyLegalDocuments) {
		this.stockholderCompanyLegalDocuments = stockholderCompanyLegalDocuments;
	}

	public com.facebank.enterprises.StockholderPersonIdentificationDocumentsData getIdentifications() {
		return this.identifications;
	}

	public void setIdentifications(
			com.facebank.enterprises.StockholderPersonIdentificationDocumentsData identifications) {
		this.identifications = identifications;
	}

	public java.lang.String getNationalityStockholder() {
		return this.nationalityStockholder;
	}

	public void setNationalityStockholder(
			java.lang.String nationalityStockholder) {
		this.nationalityStockholder = nationalityStockholder;
	}

	public StockholderDocumentsData(
			com.facebank.enterprises.StockholderPersonGeneralDocumentsData stockholderPersonGeneralDocuments,
			com.facebank.enterprises.StockholderPersonFinancialDocumentsData stockholderPersonFinancialDocuments,
			com.facebank.enterprises.StockholderCompanyGeneralDocumentsData stockholderCompanyGeneralDocuments,
			com.facebank.enterprises.StockholderCompanyFinancialDocumentsData stockholderCompanyFinancialDocuments,
			java.lang.String type,
			java.lang.String idStockholder,
			java.lang.String nameStockholder,
			com.facebank.enterprises.StockholderCompanyLegalDocumentsData stockholderCompanyLegalDocuments,
			com.facebank.enterprises.StockholderPersonIdentificationDocumentsData identifications,
			java.lang.String nationalityStockholder) {
		this.stockholderPersonGeneralDocuments = stockholderPersonGeneralDocuments;
		this.stockholderPersonFinancialDocuments = stockholderPersonFinancialDocuments;
		this.stockholderCompanyGeneralDocuments = stockholderCompanyGeneralDocuments;
		this.stockholderCompanyFinancialDocuments = stockholderCompanyFinancialDocuments;
		this.type = type;
		this.idStockholder = idStockholder;
		this.nameStockholder = nameStockholder;
		this.stockholderCompanyLegalDocuments = stockholderCompanyLegalDocuments;
		this.identifications = identifications;
		this.nationalityStockholder = nationalityStockholder;
	}

}