package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholdersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer number;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private SubstockholdersDataList subStockholders;

	private java.lang.String signatory;

	private java.lang.String nameStockholder;

	private java.lang.String nationalityStockholder;

	private java.lang.String typeStockholder;

	private java.lang.Double participationStockholder;

	private java.lang.String surNameStockholder;

	private java.lang.String secondSurNameStockholder;

	private java.lang.String positionStockholder;

	private java.lang.String idStockholder;

	public StockholdersData() {
	}

	public java.lang.Integer getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.Integer number) {
		this.number = number;
	}

	public java.lang.String getSignatory() {
		return this.signatory;
	}

	public void setSignatory(java.lang.String signatory) {
		this.signatory = signatory;
	}

	public java.lang.String getNameStockholder() {
		return this.nameStockholder;
	}

	public void setNameStockholder(java.lang.String nameStockholder) {
		this.nameStockholder = nameStockholder;
	}

	public java.lang.String getNationalityStockholder() {
		return this.nationalityStockholder;
	}

	public void setNationalityStockholder(
			java.lang.String nationalityStockholder) {
		this.nationalityStockholder = nationalityStockholder;
	}

	public java.lang.String getTypeStockholder() {
		return this.typeStockholder;
	}

	public void setTypeStockholder(java.lang.String typeStockholder) {
		this.typeStockholder = typeStockholder;
	}

	public java.lang.Double getParticipationStockholder() {
		return this.participationStockholder;
	}

	public void setParticipationStockholder(
			java.lang.Double participationStockholder) {
		this.participationStockholder = participationStockholder;
	}

	public java.lang.String getSurNameStockholder() {
		return this.surNameStockholder;
	}

	public void setSurNameStockholder(java.lang.String surNameStockholder) {
		this.surNameStockholder = surNameStockholder;
	}

	public java.lang.String getSecondSurNameStockholder() {
		return this.secondSurNameStockholder;
	}

	public void setSecondSurNameStockholder(
			java.lang.String secondSurNameStockholder) {
		this.secondSurNameStockholder = secondSurNameStockholder;
	}

	public java.lang.String getPositionStockholder() {
		return this.positionStockholder;
	}

	public void setPositionStockholder(java.lang.String positionStockholder) {
		this.positionStockholder = positionStockholder;
	}

	public java.lang.String getIdStockholder() {
		return this.idStockholder;
	}

	public void setIdStockholder(java.lang.String idStockholder) {
		this.idStockholder = idStockholder;
	}

	public com.facebank.enterprises.SubstockholdersDataList getSubStockholders() {
		return this.subStockholders;
	}

	public void setSubStockholders(
			com.facebank.enterprises.SubstockholdersDataList subStockholders) {
		this.subStockholders = subStockholders;
	}

	public StockholdersData(java.lang.Integer number,
			com.facebank.enterprises.SubstockholdersDataList subStockholders,
			java.lang.String signatory, java.lang.String nameStockholder,
			java.lang.String nationalityStockholder,
			java.lang.String typeStockholder,
			java.lang.Double participationStockholder,
			java.lang.String surNameStockholder,
			java.lang.String secondSurNameStockholder,
			java.lang.String positionStockholder, java.lang.String idStockholder) {
		this.number = number;
		this.subStockholders = subStockholders;
		this.signatory = signatory;
		this.nameStockholder = nameStockholder;
		this.nationalityStockholder = nationalityStockholder;
		this.typeStockholder = typeStockholder;
		this.participationStockholder = participationStockholder;
		this.surNameStockholder = surNameStockholder;
		this.secondSurNameStockholder = secondSurNameStockholder;
		this.positionStockholder = positionStockholder;
		this.idStockholder = idStockholder;
	}

}