package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderCompanyLegalDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.DocumentTypeData> benefitialDocumentation;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> constitutiveRecord;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> meetingMinutes;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> sharesTitle;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> statutoryChanges;

	public StockholderCompanyLegalDocumentsData() {
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getBenefitialDocumentation() {
		return this.benefitialDocumentation;
	}

	public void setBenefitialDocumentation(
			java.util.List<com.facebank.enterprises.DocumentTypeData> benefitialDocumentation) {
		this.benefitialDocumentation = benefitialDocumentation;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getConstitutiveRecord() {
		return this.constitutiveRecord;
	}

	public void setConstitutiveRecord(
			java.util.List<com.facebank.enterprises.DocumentTypeData> constitutiveRecord) {
		this.constitutiveRecord = constitutiveRecord;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getMeetingMinutes() {
		return this.meetingMinutes;
	}

	public void setMeetingMinutes(
			java.util.List<com.facebank.enterprises.DocumentTypeData> meetingMinutes) {
		this.meetingMinutes = meetingMinutes;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getSharesTitle() {
		return this.sharesTitle;
	}

	public void setSharesTitle(
			java.util.List<com.facebank.enterprises.DocumentTypeData> sharesTitle) {
		this.sharesTitle = sharesTitle;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getStatutoryChanges() {
		return this.statutoryChanges;
	}

	public void setStatutoryChanges(
			java.util.List<com.facebank.enterprises.DocumentTypeData> statutoryChanges) {
		this.statutoryChanges = statutoryChanges;
	}

	public StockholderCompanyLegalDocumentsData(
			java.util.List<com.facebank.enterprises.DocumentTypeData> benefitialDocumentation,
			java.util.List<com.facebank.enterprises.DocumentTypeData> constitutiveRecord,
			java.util.List<com.facebank.enterprises.DocumentTypeData> meetingMinutes,
			java.util.List<com.facebank.enterprises.DocumentTypeData> sharesTitle,
			java.util.List<com.facebank.enterprises.DocumentTypeData> statutoryChanges) {
		this.benefitialDocumentation = benefitialDocumentation;
		this.constitutiveRecord = constitutiveRecord;
		this.meetingMinutes = meetingMinutes;
		this.sharesTitle = sharesTitle;
		this.statutoryChanges = statutoryChanges;
	}

}