package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderDocumentsData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.DocumentTypeData> identifications;

	private java.util.List<com.facebank.enterprises.StockholderPersonGeneralDocumentsData> stockholderPersonGeneralDocuments;

	private java.util.List<com.facebank.enterprises.StockholderPersonFinancialDocumentsData> stockholderPersonFinancialDocuments;

	private java.util.List<com.facebank.enterprises.StockholderCompanyGeneralDocumentsData> stockholderCompanyGeneralDocuments;

	private java.util.List<com.facebank.enterprises.StockholderCompanyFinancialDocumentsData> stockholderCompanyFinancialDocuments;

	private String type;

	private String idStockholder;

	private String nameStockholder;

	private java.util.List<com.facebank.enterprises.StockholderCompanyLegalDocumentsData> stockholderCompanyLegalDocuments;

	public StockholderDocumentsData() {
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getIdentifications() {
		return this.identifications;
	}

	public void setIdentifications(
			java.util.List<com.facebank.enterprises.DocumentTypeData> identifications) {
		this.identifications = identifications;
	}

	public java.util.List<com.facebank.enterprises.StockholderPersonGeneralDocumentsData> getStockholderPersonGeneralDocuments() {
		return this.stockholderPersonGeneralDocuments;
	}

	public void setStockholderPersonGeneralDocuments(
			java.util.List<com.facebank.enterprises.StockholderPersonGeneralDocumentsData> stockholderPersonGeneralDocuments) {
		this.stockholderPersonGeneralDocuments = stockholderPersonGeneralDocuments;
	}

	public java.util.List<com.facebank.enterprises.StockholderPersonFinancialDocumentsData> getStockholderPersonFinancialDocuments() {
		return this.stockholderPersonFinancialDocuments;
	}

	public void setStockholderPersonFinancialDocuments(
			java.util.List<com.facebank.enterprises.StockholderPersonFinancialDocumentsData> stockholderPersonFinancialDocuments) {
		this.stockholderPersonFinancialDocuments = stockholderPersonFinancialDocuments;
	}

	public java.util.List<com.facebank.enterprises.StockholderCompanyGeneralDocumentsData> getStockholderCompanyGeneralDocuments() {
		return this.stockholderCompanyGeneralDocuments;
	}

	public void setStockholderCompanyGeneralDocuments(
			java.util.List<com.facebank.enterprises.StockholderCompanyGeneralDocumentsData> stockholderCompanyGeneralDocuments) {
		this.stockholderCompanyGeneralDocuments = stockholderCompanyGeneralDocuments;
	}

	public java.util.List<com.facebank.enterprises.StockholderCompanyFinancialDocumentsData> getStockholderCompanyFinancialDocuments() {
		return this.stockholderCompanyFinancialDocuments;
	}

	public void setStockholderCompanyFinancialDocuments(
			java.util.List<com.facebank.enterprises.StockholderCompanyFinancialDocumentsData> stockholderCompanyFinancialDocuments) {
		this.stockholderCompanyFinancialDocuments = stockholderCompanyFinancialDocuments;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getIdStockholder() {
		return this.idStockholder;
	}

	public void setIdStockholder(java.lang.String idStockholder) {
		this.idStockholder = idStockholder;
	}

	public java.lang.String getNameStockholder() {
		return this.nameStockholder;
	}

	public void setNameStockholder(java.lang.String nameStockholder) {
		this.nameStockholder = nameStockholder;
	}

	public java.util.List<com.facebank.enterprises.StockholderCompanyLegalDocumentsData> getStockholderCompanyLegalDocuments() {
		return this.stockholderCompanyLegalDocuments;
	}

	public void setStockholderCompanyLegalDocuments(
			java.util.List<com.facebank.enterprises.StockholderCompanyLegalDocumentsData> stockholderCompanyLegalDocuments) {
		this.stockholderCompanyLegalDocuments = stockholderCompanyLegalDocuments;
	}

	public StockholderDocumentsData(
			java.util.List<com.facebank.enterprises.DocumentTypeData> identifications,
			java.util.List<com.facebank.enterprises.StockholderPersonGeneralDocumentsData> stockholderPersonGeneralDocuments,
			java.util.List<com.facebank.enterprises.StockholderPersonFinancialDocumentsData> stockholderPersonFinancialDocuments,
			java.util.List<com.facebank.enterprises.StockholderCompanyGeneralDocumentsData> stockholderCompanyGeneralDocuments,
			java.util.List<com.facebank.enterprises.StockholderCompanyFinancialDocumentsData> stockholderCompanyFinancialDocuments,
			java.lang.String type,
			java.lang.String idStockholder,
			java.lang.String nameStockholder,
			java.util.List<com.facebank.enterprises.StockholderCompanyLegalDocumentsData> stockholderCompanyLegalDocuments) {
		this.identifications = identifications;
		this.stockholderPersonGeneralDocuments = stockholderPersonGeneralDocuments;
		this.stockholderPersonFinancialDocuments = stockholderPersonFinancialDocuments;
		this.stockholderCompanyGeneralDocuments = stockholderCompanyGeneralDocuments;
		this.stockholderCompanyFinancialDocuments = stockholderCompanyFinancialDocuments;
		this.type = type;
		this.idStockholder = idStockholder;
		this.nameStockholder = nameStockholder;
		this.stockholderCompanyLegalDocuments = stockholderCompanyLegalDocuments;
	}

}