package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderCompanyFinancialDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.DocumentTypeData> bankReferences;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> financialStatements;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> taxReturn;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> projectedCashFlow;
	private java.util.List<com.facebank.enterprises.DocumentTypeData> businessProjection;

	public StockholderCompanyFinancialDocumentsData() {
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getBankReferences() {
		return this.bankReferences;
	}

	public void setBankReferences(
			java.util.List<com.facebank.enterprises.DocumentTypeData> bankReferences) {
		this.bankReferences = bankReferences;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getFinancialStatements() {
		return this.financialStatements;
	}

	public void setFinancialStatements(
			java.util.List<com.facebank.enterprises.DocumentTypeData> financialStatements) {
		this.financialStatements = financialStatements;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getTaxReturn() {
		return this.taxReturn;
	}

	public void setTaxReturn(
			java.util.List<com.facebank.enterprises.DocumentTypeData> taxReturn) {
		this.taxReturn = taxReturn;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getProjectedCashFlow() {
		return this.projectedCashFlow;
	}

	public void setProjectedCashFlow(
			java.util.List<com.facebank.enterprises.DocumentTypeData> projectedCashFlow) {
		this.projectedCashFlow = projectedCashFlow;
	}

	public java.util.List<com.facebank.enterprises.DocumentTypeData> getBusinessProjection() {
		return this.businessProjection;
	}

	public void setBusinessProjection(
			java.util.List<com.facebank.enterprises.DocumentTypeData> businessProjection) {
		this.businessProjection = businessProjection;
	}

	public StockholderCompanyFinancialDocumentsData(
			java.util.List<com.facebank.enterprises.DocumentTypeData> bankReferences,
			java.util.List<com.facebank.enterprises.DocumentTypeData> financialStatements,
			java.util.List<com.facebank.enterprises.DocumentTypeData> taxReturn,
			java.util.List<com.facebank.enterprises.DocumentTypeData> projectedCashFlow,
			java.util.List<com.facebank.enterprises.DocumentTypeData> businessProjection) {
		this.bankReferences = bankReferences;
		this.financialStatements = financialStatements;
		this.taxReturn = taxReturn;
		this.projectedCashFlow = projectedCashFlow;
		this.businessProjection = businessProjection;
	}

}