package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderCompanyLegalDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private DocumentTypeDataList benefitialDocumentation;
	private DocumentTypeDataList constitutiveRecord;
	private DocumentTypeDataList meetingMinutes;
	private DocumentTypeDataList sharesTitle;
	private DocumentTypeDataList statutoryChanges;

	public StockholderCompanyLegalDocumentsData() {
	}

	public com.facebank.enterprises.DocumentTypeDataList getBenefitialDocumentation() {
		return this.benefitialDocumentation;
	}

	public void setBenefitialDocumentation(
			com.facebank.enterprises.DocumentTypeDataList benefitialDocumentation) {
		this.benefitialDocumentation = benefitialDocumentation;
	}

	public com.facebank.enterprises.DocumentTypeDataList getConstitutiveRecord() {
		return this.constitutiveRecord;
	}

	public void setConstitutiveRecord(
			com.facebank.enterprises.DocumentTypeDataList constitutiveRecord) {
		this.constitutiveRecord = constitutiveRecord;
	}

	public com.facebank.enterprises.DocumentTypeDataList getMeetingMinutes() {
		return this.meetingMinutes;
	}

	public void setMeetingMinutes(
			com.facebank.enterprises.DocumentTypeDataList meetingMinutes) {
		this.meetingMinutes = meetingMinutes;
	}

	public com.facebank.enterprises.DocumentTypeDataList getSharesTitle() {
		return this.sharesTitle;
	}

	public void setSharesTitle(
			com.facebank.enterprises.DocumentTypeDataList sharesTitle) {
		this.sharesTitle = sharesTitle;
	}

	public com.facebank.enterprises.DocumentTypeDataList getStatutoryChanges() {
		return this.statutoryChanges;
	}

	public void setStatutoryChanges(
			com.facebank.enterprises.DocumentTypeDataList statutoryChanges) {
		this.statutoryChanges = statutoryChanges;
	}

	public StockholderCompanyLegalDocumentsData(
			com.facebank.enterprises.DocumentTypeDataList benefitialDocumentation,
			com.facebank.enterprises.DocumentTypeDataList constitutiveRecord,
			com.facebank.enterprises.DocumentTypeDataList meetingMinutes,
			com.facebank.enterprises.DocumentTypeDataList sharesTitle,
			com.facebank.enterprises.DocumentTypeDataList statutoryChanges) {
		this.benefitialDocumentation = benefitialDocumentation;
		this.constitutiveRecord = constitutiveRecord;
		this.meetingMinutes = meetingMinutes;
		this.sharesTitle = sharesTitle;
		this.statutoryChanges = statutoryChanges;
	}

}