package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholdersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer number;

	private java.lang.String signatory;

	private java.lang.String nameStockholder;

	private java.lang.String nationalityStockholder;

	private java.lang.String typeStockholder;

	private java.lang.Double participationStockholder;

	private java.lang.String surNameStockholder;

	private java.lang.String secondSurNameStockholder;

	private java.lang.String positionStockholder;

	private java.lang.String idStockholder;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private com.facebank.enterprises.FinalBeneficiaryDataList finalBeneficiaries;

	private java.lang.String secondNameStockholder;

	private java.lang.String dateStockholder;

	private java.lang.String emailStockholder;

	private java.lang.String addressStockholder;

	private java.lang.String cityStockholder;

	private java.lang.String stateStockholder;

	private java.lang.String countryStockholder;

	private java.lang.Integer idNumberStockholder;

	private java.lang.String issuingCountryStockholder;

	public StockholdersData() {
	}

	public java.lang.Integer getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.Integer number) {
		this.number = number;
	}

	public java.lang.String getSignatory() {
		return this.signatory;
	}

	public void setSignatory(java.lang.String signatory) {
		this.signatory = signatory;
	}

	public java.lang.String getNameStockholder() {
		return this.nameStockholder;
	}

	public void setNameStockholder(java.lang.String nameStockholder) {
		this.nameStockholder = nameStockholder;
	}

	public java.lang.String getNationalityStockholder() {
		return this.nationalityStockholder;
	}

	public void setNationalityStockholder(
			java.lang.String nationalityStockholder) {
		this.nationalityStockholder = nationalityStockholder;
	}

	public java.lang.String getTypeStockholder() {
		return this.typeStockholder;
	}

	public void setTypeStockholder(java.lang.String typeStockholder) {
		this.typeStockholder = typeStockholder;
	}

	public java.lang.Double getParticipationStockholder() {
		return this.participationStockholder;
	}

	public void setParticipationStockholder(
			java.lang.Double participationStockholder) {
		this.participationStockholder = participationStockholder;
	}

	public java.lang.String getSurNameStockholder() {
		return this.surNameStockholder;
	}

	public void setSurNameStockholder(java.lang.String surNameStockholder) {
		this.surNameStockholder = surNameStockholder;
	}

	public java.lang.String getSecondSurNameStockholder() {
		return this.secondSurNameStockholder;
	}

	public void setSecondSurNameStockholder(
			java.lang.String secondSurNameStockholder) {
		this.secondSurNameStockholder = secondSurNameStockholder;
	}

	public java.lang.String getPositionStockholder() {
		return this.positionStockholder;
	}

	public void setPositionStockholder(java.lang.String positionStockholder) {
		this.positionStockholder = positionStockholder;
	}

	public java.lang.String getIdStockholder() {
		return this.idStockholder;
	}

	public void setIdStockholder(java.lang.String idStockholder) {
		this.idStockholder = idStockholder;
	}

	public com.facebank.enterprises.FinalBeneficiaryDataList getFinalBeneficiaries() {
		return this.finalBeneficiaries;
	}

	public void setFinalBeneficiaries(
			com.facebank.enterprises.FinalBeneficiaryDataList finalBeneficiaries) {
		this.finalBeneficiaries = finalBeneficiaries;
	}

	public java.lang.String getSecondNameStockholder() {
		return this.secondNameStockholder;
	}

	public void setSecondNameStockholder(java.lang.String secondNameStockholder) {
		this.secondNameStockholder = secondNameStockholder;
	}

	public java.lang.String getDateStockholder() {
		return this.dateStockholder;
	}

	public void setDateStockholder(java.lang.String dateStockholder) {
		this.dateStockholder = dateStockholder;
	}

	public java.lang.String getEmailStockholder() {
		return this.emailStockholder;
	}

	public void setEmailStockholder(java.lang.String emailStockholder) {
		this.emailStockholder = emailStockholder;
	}

	public java.lang.String getAddressStockholder() {
		return this.addressStockholder;
	}

	public void setAddressStockholder(java.lang.String addressStockholder) {
		this.addressStockholder = addressStockholder;
	}

	public java.lang.String getCityStockholder() {
		return this.cityStockholder;
	}

	public void setCityStockholder(java.lang.String cityStockholder) {
		this.cityStockholder = cityStockholder;
	}

	public java.lang.String getStateStockholder() {
		return this.stateStockholder;
	}

	public void setStateStockholder(java.lang.String stateStockholder) {
		this.stateStockholder = stateStockholder;
	}

	public java.lang.String getCountryStockholder() {
		return this.countryStockholder;
	}

	public void setCountryStockholder(java.lang.String countryStockholder) {
		this.countryStockholder = countryStockholder;
	}

	public java.lang.Integer getIdNumberStockholder() {
		return this.idNumberStockholder;
	}

	public void setIdNumberStockholder(java.lang.Integer idNumberStockholder) {
		this.idNumberStockholder = idNumberStockholder;
	}

	public java.lang.String getIssuingCountryStockholder() {
		return this.issuingCountryStockholder;
	}

	public void setIssuingCountryStockholder(
			java.lang.String issuingCountryStockholder) {
		this.issuingCountryStockholder = issuingCountryStockholder;
	}

	public StockholdersData(
			java.lang.Integer number,
			java.lang.String signatory,
			java.lang.String nameStockholder,
			java.lang.String nationalityStockholder,
			java.lang.String typeStockholder,
			java.lang.Double participationStockholder,
			java.lang.String surNameStockholder,
			java.lang.String secondSurNameStockholder,
			java.lang.String positionStockholder,
			java.lang.String idStockholder,
			com.facebank.enterprises.FinalBeneficiaryDataList finalBeneficiaries,
			java.lang.String secondNameStockholder,
			java.lang.String dateStockholder,
			java.lang.String emailStockholder,
			java.lang.String addressStockholder,
			java.lang.String cityStockholder,
			java.lang.String stateStockholder,
			java.lang.String countryStockholder,
			java.lang.Integer idNumberStockholder,
			java.lang.String issuingCountryStockholder) {
		this.number = number;
		this.signatory = signatory;
		this.nameStockholder = nameStockholder;
		this.nationalityStockholder = nationalityStockholder;
		this.typeStockholder = typeStockholder;
		this.participationStockholder = participationStockholder;
		this.surNameStockholder = surNameStockholder;
		this.secondSurNameStockholder = secondSurNameStockholder;
		this.positionStockholder = positionStockholder;
		this.idStockholder = idStockholder;
		this.finalBeneficiaries = finalBeneficiaries;
		this.secondNameStockholder = secondNameStockholder;
		this.dateStockholder = dateStockholder;
		this.emailStockholder = emailStockholder;
		this.addressStockholder = addressStockholder;
		this.cityStockholder = cityStockholder;
		this.stateStockholder = stateStockholder;
		this.countryStockholder = countryStockholder;
		this.idNumberStockholder = idNumberStockholder;
		this.issuingCountryStockholder = issuingCountryStockholder;
	}

}