package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderCompanyGeneralDocumentsData
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private DocumentTypeDataList evidence;
	private DocumentTypeDataList identifications;

	private com.facebank.enterprises.DocumentTypeDataList w8_w9;

	public StockholderCompanyGeneralDocumentsData() {
	}

	public com.facebank.enterprises.DocumentTypeDataList getEvidence() {
		return this.evidence;
	}

	public void setEvidence(
			com.facebank.enterprises.DocumentTypeDataList evidence) {
		this.evidence = evidence;
	}

	public com.facebank.enterprises.DocumentTypeDataList getIdentifications() {
		return this.identifications;
	}

	public void setIdentifications(
			com.facebank.enterprises.DocumentTypeDataList identifications) {
		this.identifications = identifications;
	}

	public com.facebank.enterprises.DocumentTypeDataList getW8_w9() {
		return this.w8_w9;
	}

	public void setW8_w9(com.facebank.enterprises.DocumentTypeDataList w8_w9) {
		this.w8_w9 = w8_w9;
	}

	public StockholderCompanyGeneralDocumentsData(
			com.facebank.enterprises.DocumentTypeDataList evidence,
			com.facebank.enterprises.DocumentTypeDataList identifications,
			com.facebank.enterprises.DocumentTypeDataList w8_w9) {
		this.evidence = evidence;
		this.identifications = identifications;
		this.w8_w9 = w8_w9;
	}

}