package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StockholderDocumentsDataList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.StockholderDocumentsData> stockholderDocumentsData;

	public StockholderDocumentsDataList() {
	}

	public java.util.List<com.facebank.enterprises.StockholderDocumentsData> getStockholderDocumentsData() {
		return this.stockholderDocumentsData;
	}

	public void setStockholderDocumentsData(
			java.util.List<com.facebank.enterprises.StockholderDocumentsData> stockholderDocumentsData) {
		this.stockholderDocumentsData = stockholderDocumentsData;
	}

	public StockholderDocumentsDataList(
			java.util.List<com.facebank.enterprises.StockholderDocumentsData> stockholderDocumentsData) {
		this.stockholderDocumentsData = stockholderDocumentsData;
	}

}