package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubstockholdersDataList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.enterprises.SubstockholdersData> substockholdersData;

	public SubstockholdersDataList() {
	}

	public java.util.List<com.facebank.enterprises.SubstockholdersData> getSubstockholdersData() {
		return this.substockholdersData;
	}

	public void setSubstockholdersData(
			java.util.List<com.facebank.enterprises.SubstockholdersData> substockholdersData) {
		this.substockholdersData = substockholdersData;
	}

	public SubstockholdersDataList(
			java.util.List<com.facebank.enterprises.SubstockholdersData> substockholdersData) {
		this.substockholdersData = substockholdersData;
	}

}