package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubStockholdersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String signatory;

	private java.lang.String idStockholderRelated;

	private java.lang.String companyName;

	private java.lang.String nameSubStockholder;

	private java.lang.Double participationSubStockholder;

	private java.lang.String secondSurNameSubStockholder;

	private java.lang.String surNameSubStockholder;

	private java.lang.String typeSubStockholder;

	private String idNumberSubStockholder;

	private java.lang.String secondNameSubStockholder;

	private java.lang.String birthDateSubStockholder;

	private java.lang.String emailSubStockholder;

	private java.lang.String addressSubStockholder;

	private java.lang.String citySubStockholder;

	private java.lang.String stateSubStockholder;

	private java.lang.String countrySubStockholder;

	private java.lang.String issuingCountrySubStockholder;

	public SubStockholdersData() {
	}

	public java.lang.String getSignatory() {
		return this.signatory;
	}

	public void setSignatory(java.lang.String signatory) {
		this.signatory = signatory;
	}

	public java.lang.String getIdStockholderRelated() {
		return this.idStockholderRelated;
	}

	public void setIdStockholderRelated(java.lang.String idStockholderRelated) {
		this.idStockholderRelated = idStockholderRelated;
	}

	public java.lang.String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(java.lang.String companyName) {
		this.companyName = companyName;
	}

	public java.lang.String getNameSubStockholder() {
		return this.nameSubStockholder;
	}

	public void setNameSubStockholder(java.lang.String nameSubStockholder) {
		this.nameSubStockholder = nameSubStockholder;
	}

	public java.lang.Double getParticipationSubStockholder() {
		return this.participationSubStockholder;
	}

	public void setParticipationSubStockholder(
			java.lang.Double participationSubStockholder) {
		this.participationSubStockholder = participationSubStockholder;
	}

	public java.lang.String getSecondSurNameSubStockholder() {
		return this.secondSurNameSubStockholder;
	}

	public void setSecondSurNameSubStockholder(
			java.lang.String secondSurNameSubStockholder) {
		this.secondSurNameSubStockholder = secondSurNameSubStockholder;
	}

	public java.lang.String getSurNameSubStockholder() {
		return this.surNameSubStockholder;
	}

	public void setSurNameSubStockholder(java.lang.String surNameSubStockholder) {
		this.surNameSubStockholder = surNameSubStockholder;
	}

	public java.lang.String getTypeSubStockholder() {
		return this.typeSubStockholder;
	}

	public void setTypeSubStockholder(java.lang.String typeSubStockholder) {
		this.typeSubStockholder = typeSubStockholder;
	}

	public java.lang.String getSecondNameSubStockholder() {
		return this.secondNameSubStockholder;
	}

	public void setSecondNameSubStockholder(
			java.lang.String secondNameSubStockholder) {
		this.secondNameSubStockholder = secondNameSubStockholder;
	}

	public java.lang.String getBirthDateSubStockholder() {
		return this.birthDateSubStockholder;
	}

	public void setBirthDateSubStockholder(
			java.lang.String birthDateSubStockholder) {
		this.birthDateSubStockholder = birthDateSubStockholder;
	}

	public java.lang.String getEmailSubStockholder() {
		return this.emailSubStockholder;
	}

	public void setEmailSubStockholder(java.lang.String emailSubStockholder) {
		this.emailSubStockholder = emailSubStockholder;
	}

	public java.lang.String getAddressSubStockholder() {
		return this.addressSubStockholder;
	}

	public void setAddressSubStockholder(java.lang.String addressSubStockholder) {
		this.addressSubStockholder = addressSubStockholder;
	}

	public java.lang.String getCitySubStockholder() {
		return this.citySubStockholder;
	}

	public void setCitySubStockholder(java.lang.String citySubStockholder) {
		this.citySubStockholder = citySubStockholder;
	}

	public java.lang.String getStateSubStockholder() {
		return this.stateSubStockholder;
	}

	public void setStateSubStockholder(java.lang.String stateSubStockholder) {
		this.stateSubStockholder = stateSubStockholder;
	}

	public java.lang.String getCountrySubStockholder() {
		return this.countrySubStockholder;
	}

	public void setCountrySubStockholder(java.lang.String countrySubStockholder) {
		this.countrySubStockholder = countrySubStockholder;
	}

	public java.lang.String getIssuingCountrySubStockholder() {
		return this.issuingCountrySubStockholder;
	}

	public void setIssuingCountrySubStockholder(
			java.lang.String issuingCountrySubStockholder) {
		this.issuingCountrySubStockholder = issuingCountrySubStockholder;
	}

	public java.lang.String getIdNumberSubStockholder() {
		return this.idNumberSubStockholder;
	}

	public void setIdNumberSubStockholder(
			java.lang.String idNumberSubStockholder) {
		this.idNumberSubStockholder = idNumberSubStockholder;
	}

	public SubStockholdersData(java.lang.String signatory,
			java.lang.String idStockholderRelated,
			java.lang.String companyName, java.lang.String nameSubStockholder,
			java.lang.Double participationSubStockholder,
			java.lang.String secondSurNameSubStockholder,
			java.lang.String surNameSubStockholder,
			java.lang.String typeSubStockholder,
			java.lang.String idNumberSubStockholder,
			java.lang.String secondNameSubStockholder,
			java.lang.String birthDateSubStockholder,
			java.lang.String emailSubStockholder,
			java.lang.String addressSubStockholder,
			java.lang.String citySubStockholder,
			java.lang.String stateSubStockholder,
			java.lang.String countrySubStockholder,
			java.lang.String issuingCountrySubStockholder) {
		this.signatory = signatory;
		this.idStockholderRelated = idStockholderRelated;
		this.companyName = companyName;
		this.nameSubStockholder = nameSubStockholder;
		this.participationSubStockholder = participationSubStockholder;
		this.secondSurNameSubStockholder = secondSurNameSubStockholder;
		this.surNameSubStockholder = surNameSubStockholder;
		this.typeSubStockholder = typeSubStockholder;
		this.idNumberSubStockholder = idNumberSubStockholder;
		this.secondNameSubStockholder = secondNameSubStockholder;
		this.birthDateSubStockholder = birthDateSubStockholder;
		this.emailSubStockholder = emailSubStockholder;
		this.addressSubStockholder = addressSubStockholder;
		this.citySubStockholder = citySubStockholder;
		this.stateSubStockholder = stateSubStockholder;
		this.countrySubStockholder = countrySubStockholder;
		this.issuingCountrySubStockholder = issuingCountrySubStockholder;
	}

}