package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubstockholdersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idStockholder;
	private java.lang.String nameStockholder;
	private java.lang.String nationalityStockholder;

	private java.lang.Integer number;

	private java.lang.Double participationStockholder;

	private java.lang.String positionStockholder;

	private java.lang.String secondSurNameStockholder;

	private java.lang.String signatory;

	private java.lang.String surNameStockholder;

	private java.lang.String typeStockholder;

	public SubstockholdersData() {
	}

	public java.lang.String getIdStockholder() {
		return this.idStockholder;
	}

	public void setIdStockholder(java.lang.String idStockholder) {
		this.idStockholder = idStockholder;
	}

	public java.lang.String getNameStockholder() {
		return this.nameStockholder;
	}

	public void setNameStockholder(java.lang.String nameStockholder) {
		this.nameStockholder = nameStockholder;
	}

	public java.lang.String getNationalityStockholder() {
		return this.nationalityStockholder;
	}

	public void setNationalityStockholder(
			java.lang.String nationalityStockholder) {
		this.nationalityStockholder = nationalityStockholder;
	}

	public java.lang.Integer getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.Integer number) {
		this.number = number;
	}

	public java.lang.Double getParticipationStockholder() {
		return this.participationStockholder;
	}

	public void setParticipationStockholder(
			java.lang.Double participationStockholder) {
		this.participationStockholder = participationStockholder;
	}

	public java.lang.String getPositionStockholder() {
		return this.positionStockholder;
	}

	public void setPositionStockholder(java.lang.String positionStockholder) {
		this.positionStockholder = positionStockholder;
	}

	public java.lang.String getSecondSurNameStockholder() {
		return this.secondSurNameStockholder;
	}

	public void setSecondSurNameStockholder(
			java.lang.String secondSurNameStockholder) {
		this.secondSurNameStockholder = secondSurNameStockholder;
	}

	public java.lang.String getSignatory() {
		return this.signatory;
	}

	public void setSignatory(java.lang.String signatory) {
		this.signatory = signatory;
	}

	public java.lang.String getSurNameStockholder() {
		return this.surNameStockholder;
	}

	public void setSurNameStockholder(java.lang.String surNameStockholder) {
		this.surNameStockholder = surNameStockholder;
	}

	public java.lang.String getTypeStockholder() {
		return this.typeStockholder;
	}

	public void setTypeStockholder(java.lang.String typeStockholder) {
		this.typeStockholder = typeStockholder;
	}

	public SubstockholdersData(java.lang.String idStockholder,
			java.lang.String nameStockholder,
			java.lang.String nationalityStockholder, java.lang.Integer number,
			java.lang.Double participationStockholder,
			java.lang.String positionStockholder,
			java.lang.String secondSurNameStockholder,
			java.lang.String signatory, java.lang.String surNameStockholder,
			java.lang.String typeStockholder) {
		this.idStockholder = idStockholder;
		this.nameStockholder = nameStockholder;
		this.nationalityStockholder = nationalityStockholder;
		this.number = number;
		this.participationStockholder = participationStockholder;
		this.positionStockholder = positionStockholder;
		this.secondSurNameStockholder = secondSurNameStockholder;
		this.signatory = signatory;
		this.surNameStockholder = surNameStockholder;
		this.typeStockholder = typeStockholder;
	}

}