package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubstockholdersDataList implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SubstockholdersDataList() {
    }




}