package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TransactionalData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String monthlyNumberSend;

	private java.lang.String monthlyValueSend;

	private java.lang.String internalMonthlyNumberSend;

	private java.lang.String internalMonthlyValueSend;

	private java.lang.String monthlyNumberReceive;

	private java.lang.String monthlyValueReceive;

	private java.lang.String internalMonthlyNumberReceive;

	private java.lang.String internalMonthlyValueReceive;

	public TransactionalData() {
	}

	public java.lang.String getMonthlyNumberSend() {
		return this.monthlyNumberSend;
	}

	public void setMonthlyNumberSend(java.lang.String monthlyNumberSend) {
		this.monthlyNumberSend = monthlyNumberSend;
	}

	public java.lang.String getMonthlyValueSend() {
		return this.monthlyValueSend;
	}

	public void setMonthlyValueSend(java.lang.String monthlyValueSend) {
		this.monthlyValueSend = monthlyValueSend;
	}

	public java.lang.String getInternalMonthlyNumberSend() {
		return this.internalMonthlyNumberSend;
	}

	public void setInternalMonthlyNumberSend(
			java.lang.String internalMonthlyNumberSend) {
		this.internalMonthlyNumberSend = internalMonthlyNumberSend;
	}

	public java.lang.String getInternalMonthlyValueSend() {
		return this.internalMonthlyValueSend;
	}

	public void setInternalMonthlyValueSend(
			java.lang.String internalMonthlyValueSend) {
		this.internalMonthlyValueSend = internalMonthlyValueSend;
	}

	public java.lang.String getMonthlyNumberReceive() {
		return this.monthlyNumberReceive;
	}

	public void setMonthlyNumberReceive(java.lang.String monthlyNumberReceive) {
		this.monthlyNumberReceive = monthlyNumberReceive;
	}

	public java.lang.String getMonthlyValueReceive() {
		return this.monthlyValueReceive;
	}

	public void setMonthlyValueReceive(java.lang.String monthlyValueReceive) {
		this.monthlyValueReceive = monthlyValueReceive;
	}

	public java.lang.String getInternalMonthlyNumberReceive() {
		return this.internalMonthlyNumberReceive;
	}

	public void setInternalMonthlyNumberReceive(
			java.lang.String internalMonthlyNumberReceive) {
		this.internalMonthlyNumberReceive = internalMonthlyNumberReceive;
	}

	public java.lang.String getInternalMonthlyValueReceive() {
		return this.internalMonthlyValueReceive;
	}

	public void setInternalMonthlyValueReceive(
			java.lang.String internalMonthlyValueReceive) {
		this.internalMonthlyValueReceive = internalMonthlyValueReceive;
	}

	public TransactionalData(java.lang.String monthlyNumberSend,
			java.lang.String monthlyValueSend,
			java.lang.String internalMonthlyNumberSend,
			java.lang.String internalMonthlyValueSend,
			java.lang.String monthlyNumberReceive,
			java.lang.String monthlyValueReceive,
			java.lang.String internalMonthlyNumberReceive,
			java.lang.String internalMonthlyValueReceive) {
		this.monthlyNumberSend = monthlyNumberSend;
		this.monthlyValueSend = monthlyValueSend;
		this.internalMonthlyNumberSend = internalMonthlyNumberSend;
		this.internalMonthlyValueSend = internalMonthlyValueSend;
		this.monthlyNumberReceive = monthlyNumberReceive;
		this.monthlyValueReceive = monthlyValueReceive;
		this.internalMonthlyNumberReceive = internalMonthlyNumberReceive;
		this.internalMonthlyValueReceive = internalMonthlyValueReceive;
	}

}