package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidDataList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<com.facebank.enterprises.ValidData> validData;

	public ValidDataList() {
	}

	public java.util.List<com.facebank.enterprises.ValidData> getValidData() {
		return this.validData;
	}

	public void setValidData(
			java.util.List<com.facebank.enterprises.ValidData> validData) {
		this.validData = validData;
	}

	public ValidDataList(
			java.util.List<com.facebank.enterprises.ValidData> validData) {
		this.validData = validData;
	}

}