package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String showName;
	private java.lang.String variableName;

	private java.lang.String indexParent;

	private java.lang.String indexChild;

	public ValidData() {
	}

	public java.lang.String getShowName() {
		return this.showName;
	}

	public void setShowName(java.lang.String showName) {
		this.showName = showName;
	}

	public java.lang.String getVariableName() {
		return this.variableName;
	}

	public void setVariableName(java.lang.String variableName) {
		this.variableName = variableName;
	}

	public java.lang.String getIndexParent() {
		return this.indexParent;
	}

	public void setIndexParent(java.lang.String indexParent) {
		this.indexParent = indexParent;
	}

	public java.lang.String getIndexChild() {
		return this.indexChild;
	}

	public void setIndexChild(java.lang.String indexChild) {
		this.indexChild = indexChild;
	}

	public ValidData(java.lang.String showName, java.lang.String variableName,
			java.lang.String indexParent, java.lang.String indexChild) {
		this.showName = showName;
		this.variableName = variableName;
		this.indexParent = indexParent;
		this.indexChild = indexChild;
	}

}