package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String showName;
	private java.lang.String variableName;

	private java.lang.String idParent;

	private java.lang.String idChild;

	public ValidData() {
	}

	public java.lang.String getShowName() {
		return this.showName;
	}

	public void setShowName(java.lang.String showName) {
		this.showName = showName;
	}

	public java.lang.String getVariableName() {
		return this.variableName;
	}

	public void setVariableName(java.lang.String variableName) {
		this.variableName = variableName;
	}

	public java.lang.String getIdParent() {
		return this.idParent;
	}

	public void setIdParent(java.lang.String idParent) {
		this.idParent = idParent;
	}

	public java.lang.String getIdChild() {
		return this.idChild;
	}

	public void setIdChild(java.lang.String idChild) {
		this.idChild = idChild;
	}

	public ValidData(java.lang.String showName, java.lang.String variableName,
			java.lang.String idParent, java.lang.String idChild) {
		this.showName = showName;
		this.variableName = variableName;
		this.idParent = idParent;
		this.idChild = idChild;
	}

}