package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String showName;
	private java.lang.String variableName;

	private java.lang.String indexStockholder;

	private java.lang.String indexSubstockholder;

	public ValidData() {
	}

	public java.lang.String getShowName() {
		return this.showName;
	}

	public void setShowName(java.lang.String showName) {
		this.showName = showName;
	}

	public java.lang.String getVariableName() {
		return this.variableName;
	}

	public void setVariableName(java.lang.String variableName) {
		this.variableName = variableName;
	}

	public java.lang.String getIndexStockholder() {
		return this.indexStockholder;
	}

	public void setIndexStockholder(java.lang.String indexStockholder) {
		this.indexStockholder = indexStockholder;
	}

	public java.lang.String getIndexSubstockholder() {
		return this.indexSubstockholder;
	}

	public void setIndexSubstockholder(java.lang.String indexSubstockholder) {
		this.indexSubstockholder = indexSubstockholder;
	}

	public ValidData(java.lang.String showName, java.lang.String variableName,
			java.lang.String indexStockholder,
			java.lang.String indexSubstockholder) {
		this.showName = showName;
		this.variableName = variableName;
		this.indexStockholder = indexStockholder;
		this.indexSubstockholder = indexSubstockholder;
	}

}