package com.facebank.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorldcheckData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer totalResults;

	public WorldcheckData() {
	}

	public java.lang.Integer getTotalResults() {
		return this.totalResults;
	}

	public void setTotalResults(java.lang.Integer totalResults) {
		this.totalResults = totalResults;
	}

	public WorldcheckData(java.lang.Integer totalResults) {
		this.totalResults = totalResults;
	}

}