package com.test.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AuthorizedList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "AUTHORIZEDLIST_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "AUTHORIZEDLIST_ID_GENERATOR", sequenceName = "AUTHORIZEDLIST_ID_SEQ")
	private java.lang.Long id;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<com.test.enterprises.Authorized> authorizedData;

	public AuthorizedList() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.List<com.test.enterprises.Authorized> getAuthorizedData() {
		return this.authorizedData;
	}

	public void setAuthorizedData(
			java.util.List<com.test.enterprises.Authorized> authorizedData) {
		this.authorizedData = authorizedData;
	}

	public AuthorizedList(java.lang.Long id,
			java.util.List<com.test.enterprises.Authorized> authorizedData) {
		this.id = id;
		this.authorizedData = authorizedData;
	}

}