package com.test.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class BusinessData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String businessTypeDescription;

	private java.lang.String productsTypeDescription;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BUSINESSDATA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "BUSINESSDATA_ID_GENERATOR", sequenceName = "BUSINESSDATA_ID_SEQ")
	private java.lang.Long id;

	public BusinessData() {
	}

	public java.lang.String getBusinessTypeDescription() {
		return this.businessTypeDescription;
	}

	public void setBusinessTypeDescription(
			java.lang.String businessTypeDescription) {
		this.businessTypeDescription = businessTypeDescription;
	}

	public java.lang.String getProductsTypeDescription() {
		return this.productsTypeDescription;
	}

	public void setProductsTypeDescription(
			java.lang.String productsTypeDescription) {
		this.productsTypeDescription = productsTypeDescription;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public BusinessData(java.lang.String businessTypeDescription,
			java.lang.String productsTypeDescription, java.lang.Long id) {
		this.businessTypeDescription = businessTypeDescription;
		this.productsTypeDescription = productsTypeDescription;
		this.id = id;
	}

}