package com.test.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ShareholdersDataList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SHAREHOLDERSDATALIST_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SHAREHOLDERSDATALIST_ID_GENERATOR", sequenceName = "SHAREHOLDERSDATALIST_ID_SEQ")
	private java.lang.Long id;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<com.test.enterprises.ShareholdersData> shareholdersData;

	public ShareholdersDataList() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.List<com.test.enterprises.ShareholdersData> getShareholdersData() {
		return this.shareholdersData;
	}

	public void setShareholdersData(
			java.util.List<com.test.enterprises.ShareholdersData> shareholdersData) {
		this.shareholdersData = shareholdersData;
	}

	public ShareholdersDataList(
			java.lang.Long id,
			java.util.List<com.test.enterprises.ShareholdersData> shareholdersData) {
		this.id = id;
		this.shareholdersData = shareholdersData;
	}

}