package com.test.enterprises;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ShareholdersData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SHAREHOLDERSDATA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SHAREHOLDERSDATA_ID_GENERATOR", sequenceName = "SHAREHOLDERSDATA_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String name;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private ShareholdersDataList subShareHolderList;

	private java.lang.String title;

	private java.lang.String entityType;

	private java.lang.String status;

	private java.lang.String enterprise;

	private java.lang.Double participationPercentage;

	public ShareholdersData() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public com.test.enterprises.ShareholdersDataList getSubShareHolderList() {
		return this.subShareHolderList;
	}

	public void setSubShareHolderList(
			com.test.enterprises.ShareholdersDataList subShareHolderList) {
		this.subShareHolderList = subShareHolderList;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(java.lang.String entityType) {
		this.entityType = entityType;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getEnterprise() {
		return this.enterprise;
	}

	public void setEnterprise(java.lang.String enterprise) {
		this.enterprise = enterprise;
	}

	public java.lang.Double getParticipationPercentage() {
		return this.participationPercentage;
	}

	public void setParticipationPercentage(
			java.lang.Double participationPercentage) {
		this.participationPercentage = participationPercentage;
	}

	public ShareholdersData(java.lang.Long id, java.lang.String name,
			com.test.enterprises.ShareholdersDataList subShareHolderList,
			java.lang.String title, java.lang.String entityType,
			java.lang.String status, java.lang.String enterprise,
			java.lang.Double participationPercentage) {
		this.id = id;
		this.name = name;
		this.subShareHolderList = subShareHolderList;
		this.title = title;
		this.entityType = entityType;
		this.status = status;
		this.enterprise = enterprise;
		this.participationPercentage = participationPercentage;
	}

}